### ISSUE TITLE
Icon Enhancement

### ISSUE THREAD

**Issue by jokerigno** [lendy007/homeassistant-skodaconnect#1]
Hi,

it's not a bug but a suggestion about icons: 

- change icon for parking lights with mdi:car-parking-lights

- change icon for car doors with mdi:car-door and mdi:car-door-lock

What do you think?

NB: I'm also creating a request for [car windows](https://github.com/Templarian/MaterialDesign/issues/5652) on MDI and I saw a request for [trunk](https://github.com/Templarian/MaterialDesign/issues/5170). Let's see if we're lucky.

Thank you!

**Comment by lendy007** [comment]
Hello,

when I have tried to add icon to binary sensor (parking lights) - I got message from HA, that this is unsupported for this entity.

For doors - I saw that it is defined as class door meaning different icon for closed or opened doors. But I am not so good at home assistant so I am not sure how to change it properly.

If you know how to perform these changes, I will really appreciate it, feel free to create a pull request with modifications, I will include it into plugin.

Thank you

**Comment by jokerigno** [comment]
oh well I'm a average guy and cannot help in programming ( I wish I had this competencies!) If you're ok I would leave the issue open waiting for help :)

**Comment by Farfar** [comment]
The parking lights and car-door icons is upcoming in a later release, I have it working in dev.
However car-door-lock won't happen since there's no pretty way of implementing it since there's no corresponding icon for unlocked.

**Comment by Farfar** [comment]
Icons have been updated in version 1.0.30 and onwards. The lock icon stays as a padlock locked/unlocked since there's no clear icon for unlocked car door. The regular mdi:car-door icon doesn't clearly show that the door is unlocked.
