### ISSUE TITLE
Login failed with error: Invalid username

### ISSUE THREAD

**Issue by vBrolin** [lendy007/homeassistant-skodaconnect#101]
Getting this error while setting up the integration:
Login failed with error: Invalid username

Same account works in the app.

**Comment by dolenec** [comment]
Same for me after HA restart:

Podrobnosti dnevnika (ERROR)

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/skodaconnect/__init__.py:790
Integration: Skoda Connect (documentation, issues)
First occurred: 13:05:03 (1 occurrences)
Last logged: 13:05:03
Error setting up Xxxxxxxxxxxxxxx for skodaconnectTraceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/skodaconnect/connection.py", line 357, in _signin_service for t in responseSoup.find('form', id='credentialsForm').find_all('input', type='hidden'): AttributeError: 'NoneType' object has no attribute 'find_all' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup result = await component.async_setup_entry(hass, self) # type: ignore File "/config/custom_components/skodaconnect/__init__.py", line 142, in async_setup_entry if not await coordinator.async_login(): File "/config/custom_components/skodaconnect/__init__.py", line 790, in async_login if await self.connection.doLogin() is False: File "/usr/local/lib/python3.9/site-packages/skodaconnect/connection.py", line 136, in doLogin return await self._authorize('skoda') File "/usr/local/lib/python3.9/site-packages/skodaconnect/connection.py", line 207, in _authorize location = await self._signin_service(req, authissuer, authorizationEndpoint) File "/usr/local/lib/python3.9/site-packages/skodaconnect/connection.py", line 366, in _signin_service raise SkodaAuthenticationException("Invalid username") skodaconnect.exceptions.SkodaAuthenticationException: Invalid username

**Comment by MarcoGos** [comment]
Exact same error as dolenec after HA restart.

**Comment by terriblefox** [comment]
Me too, cannot Login and car anymore.

**Comment by sondi2003** [comment]
I had to reinstall the integration because of a change of IP from Home Assistant. now I can no longer log in. it spins and spins, just doesn't go any further

**Comment by mze9412** [comment]
Since updating to HA  2021.12.10 yesterday :(

**Comment by kpeson** [comment]
Same for me, since yesterday..

**Comment by craigrouse** [comment]
Same here after HA restart.

**Comment by Farfar** [comment]
> Same here after HA restart. The python script attempts to retrieve the login form from the Skoda Connect web portal, and it seems the form can't be found by its id - perhaps the login form has changed. I'll do some more digging later.

Yes the login form has changed. The library is updated and a new release will be pushed soon.

**Comment by Farfar** [comment]
@craigrouse @kpeson @mze9412 @MarcoGos @dolenec @vBrolin @terriblefox @sondi2003 
Please try latest release, 1.0.63. It should also contain minor cosmetic fixes for HA 2021.12+.

**Comment by MarcoGos** [comment]
@Farfar Working like a charm again. Thanks for the quick response.

**Comment by Farfar** [comment]
Excellent! I have reports from multiple users now stating that it works so I'll close this issue.
