### ISSUE TITLE
Skoda invalid username

### ISSUE THREAD

**Issue by JanDetrez** [lendy007/homeassistant-skodaconnect#103]
Hello

The Skoda Connect integration has worked beautifully for me for many months. Although entities were unavailable before (but rarely) supposedly due to Skoda server issues, they remained unavailable for many days in the passed week. I then removed the integration, and when trying to re-add the integration, I get the error in the log of "login failed with error: invalid username". I did not change anything with regard to the credentials, and I can still login to the app, and also on https://www.skoda-connect.com/ with the same credentials. Can someone please help debug please?

**Comment by JanDetrez** [comment]
Sorry I just see the issue being reported here https://github.com/lendy007/homeassistant-skodaconnect/issues/101

**Comment by Farfar** [comment]
Make sure to update integration to latest release, 1.0.63, will require Home Assistant 2021.12 or later.
