### ISSUE TITLE
Feature request - Support for Audi

### ISSUE THREAD

**Issue by titiviking** [lendy007/homeassistant-skodaconnect#104]
The API's exposed by VW Group seem to be somehow aligned across the different brands (Skoda, VW, Audi).

Is there a way to make the integration more generic by supporting URL for the other brands (e.g. Audi) ?

This would enable new API's to be directly supported for all brands, rather than multiple integrations needing to retrofit in their own corner...

**Comment by Farfar** [comment]
> The API's exposed by VW Group seem to be somehow aligned across the different brands (Skoda, VW, Audi).
> 
> Is there a way to make the integration more generic by supporting URL for the other brands (e.g. Audi) ?
> 
> This would enable new API's to be directly supported for all brands, rather than multiple integrations needing to retrofit in their own corner...

Yes it's possible and I have started on a project to abstrakt the API and make it easier to build support for the different brands and models.
And make the code more pythonic.

I don't have nearly enough time, or experience, though to make it a reality.
