### ISSUE TITLE
"force_data_refresh" - unavailable

### ISSUE THREAD

**Issue by msandvold** [lendy007/homeassistant-skodaconnect#106]
**Describe the bug**
switch.xxxxxxx_force_data_refresh is unavailable

**Latest working release**
- v1.0.63
- HA core 2021.12.10

**Installation:**
 - Home Assistant - HACS

**Comment by Farfar** [comment]
Missing as in not existing in you hass setup?
Working fine here. Have you disabled the entity?

**Comment by msandvold** [comment]
Hi @Farfar .
It's active - but shows as unavailable - not able to togle switch
![unavailable](https://user-images.githubusercontent.com/79774666/152333907-b28a81d4-5cfa-4688-9ba0-30fa72010504.JPG)
.

**Comment by Farfar** [comment]
No idea why it would be unavailable. Have you tried restarting HA? If that doesn't work I'd need full debug logs.

**Comment by msandvold** [comment]
Hi, @Farfar 
The issue happend when I updated to core-2022.2.0 - there vere som "breaking changes in this versjon regarding "switches".
Totay I've updatet to core-2022.2.1 - the switch.xxxxxxx_force_data_refresh is back - but "looks" different
![force_update](https://user-images.githubusercontent.com/79774666/152513851-549deed3-be05-42e9-a9da-eacd9efc198f.JPG)

Is there som fix You need to do to get det slider back -like this.:
![webasto](https://user-images.githubusercontent.com/79774666/152514090-bc73fea5-7430-4e62-aed6-b50fbaf87fb8.JPG)

**Comment by Farfar** [comment]
Thanks for info.
There's probably some change to classes or similar. I'll have a look!

**Comment by msandvold** [comment]
@Farfar 
Perfect :)

**Comment by Farfar** [comment]
> @Farfar Perfect :)

Should be fixed in 1.0.66, can you verify?

**Comment by msandvold** [comment]
Verified! :)

**Comment by Farfar** [comment]
> Verified! :)

Thanks! Closing issue 🙂
