### ISSUE TITLE
Last Connected Invalid Timestamp

### ISSUE THREAD

**Issue by ZuluWhiskey** [lendy007/homeassistant-skodaconnect#113]
**Describe the bug**
The sensor this integration has created for my car's last connected time shows as "Invalid timestamp" when the state is displayed anywhere other than `Developer Tools > States`

**Latest working release**
I haven't used the integration in a while so can't answer this unfortunately.

**Debug logs**
If applicable, add debug logs. See [README](https://github.com/lendy007/homeassistant-skodaconnect#enable-debug-logging) on how to enable debug logs with response debugging.

**Installation:**
 - Home Assistant variant: Home Assistant OS
 - Python version: 3.9.7
 - Python library versions: Unknown

**Additional context**

An image of the error:
![image](https://user-images.githubusercontent.com/35011199/155394819-0abe0bdf-ea18-47d7-a838-2541f49e52f5.jpeg)

An image of the sensor state:
![image](https://user-images.githubusercontent.com/35011199/155394857-3023874d-6c58-4f0e-95fa-81a660a17727.jpeg)

An image of a known working sensor with a valid timestamp:
![image](https://user-images.githubusercontent.com/35011199/155394908-41569724-b3d2-4b00-8cd2-6f7dc0dab909.jpeg)

I came across [this thread](https://community.home-assistant.io/t/sensor-as-timestamp-rendered-invalid-timestamp-after-upgrade-to-2021-12/369526/4?u=zuluwhiskey) in the Home Assistant Community pages which states that if `device_class: timestamp` is removed the error will clear but it will mean the sensor cannot be used for time triggers in automations / scripts (which currently wouldn't work anyway)

**Comment by Farfar** [comment]
Strange since this is working fine for me?
<img width="694" alt="image" src="https://user-images.githubusercontent.com/1235384/155492913-11d7a9fc-a61b-46bd-badd-98307b3edfa4.png">

Which Home Assistant version are you running?

**Comment by ZuluWhiskey** [comment]
> Strange since this is working fine for me?
> 
> <img width="694" alt="image" src="https://user-images.githubusercontent.com/1235384/155492913-11d7a9fc-a61b-46bd-badd-98307b3edfa4.png">
> 
> 
> 
> Which Home Assistant version are you running?

That is very odd then!
I'm running the latest HA version: 2022.2.9 on Home Assistant OS

**Comment by loeffelpan** [comment]
I can help.

Brief summary: It depends on your timestamp format (non-isoformat) and the browser rendering the dashboard.

Chromium/Edge will render non-isoformat timestamp (without 'T' in the middle) correct. Other browsers (e. g. Safari on iOS and iPadOS) display "invalid timestamp".
In my case same happens with parking time sensor using `format: relative`.

See https://github.com/benct/lovelace-multiple-entity-row/issues/246 for further information.
