### ISSUE TITLE
Single departure timer without function - same with MySkoda-App

### ISSUE THREAD

**Issue by loeffelpan** [lendy007/homeassistant-skodaconnect#115]
I open an issue as discussed on discord with @Farfar.

Brief summary:
If I set single departure timer via integration or MySkoda it doesn't work.
In in the car (e-manager) there is no weekday highlighted, but maybe thats fine cause e-manager could only plan/show next seven days and MySkoda could set a date more than seven days away.

As you said I just enabled Full-API option an debug-mode for `skodaconnect.connection`.
Set timer 1 and 2 with same data. Then went to the car and fix timer 1 (selecting a weekday).
This is the logfile. Hopefully you can see something in the json-responses before and after fixing it in the car.

[home-assistant.log](https://github.com/lendy007/homeassistant-skodaconnect/files/8226817/home-assistant.log)

**Comment by Farfar** [comment]
This seems to be an API limitation, or perhaps a bug in car software. Would love to know which other cars are affected.
Mine is affected, Superb iV 2020 with 0278 software.

**Comment by loeffelpan** [comment]
I wrote another mail to skoda customer support and got an answer for this.
They say that there is an update to fix departure timers and I should contact my dealer.

Well, tomorrow my car is at the dealer for oil and service. I'll ask for that update and report.

**Comment by loeffelpan** [comment]
Got 0278 today.
I'll test tomorrow if single departure timer work again.

If not the customer support should declare which update will fix this issue.
