### ISSUE TITLE
Create a switch button for charger_max_ampere for Enyaq

### ISSUE THREAD

**Issue by are0002** [lendy007/homeassistant-skodaconnect#116]
**Is your feature request related to a problem? Please describe.**
New feature

**Describe the solution you'd like**
create a switch button instead of for Enyaq, instead of limited to "Maximum"/"Reduced"

**Describe alternatives you've considered**
unknown alternatives 

**Additional context**
It is the same behavior on the mobile app. You can choose to enable/disable Max Charging Power

**Comment by Farfar** [comment]
> **Is your feature request related to a problem? Please describe.** New feature
> 
> **Describe the solution you'd like** create a switch button instead of for Enyaq, instead of limited to "Maximum"/"Reduced"
> 
> **Describe alternatives you've considered** unknown alternatives
> 
> **Additional context** It is the same behavior on the mobile app. You can choose to enable/disable Max Charging Power

I won't implement this as it would require vehicle specific checks. Other cars have the ability to set arbitrary value for charger max ampere. Superb iV for instance can be set to 1-16 Amps.
You can accomplish what you want easy enough with a template switch calling the service https://www.home-assistant.io/integrations/switch.template/
