### ISSUE TITLE
My Skoda is not being polled every 60 seconds

### ISSUE THREAD

**Issue by mdczaplicki** [lendy007/homeassistant-skodaconnect#117]
When configuring integration - I've set poll period to 60 second. However I can see that the car is not being polled every minute. 
E.g.,  
![image](https://user-images.githubusercontent.com/9108586/161218576-3e1f0841-aed1-41da-857d-d0af2ef2089d.png)

Most often state of charge was updated is in 2 minutes intervals. However once the car got fully charged - it stopped polling.

Similar thing happened yesterday when I needed to drive the car. It wasn't polled when I was driving, it was polled few times when I reached my destination & when I was on my way back - it wasn't polled again.

Am I missing something or is it how it should work?

**Comment by Farfar** [comment]
> When configuring integration - I've set poll period to 60 second. However I can see that the car is not being polled every minute. E.g., ![image](https://user-images.githubusercontent.com/9108586/161218576-3e1f0841-aed1-41da-857d-d0af2ef2089d.png)
> 
> Most often state of charge was updated is in 2 minutes intervals. However once the car got fully charged - it stopped polling.
> 
> Similar thing happened yesterday when I needed to drive the car. It wasn't polled when I was driving, it was polled few times when I reached my destination & when I was on my way back - it wasn't polled again.
> 
> Am I missing something or is it how it should work?

The integration will poll the API in the interval you set. If there's no new data, or the data is unchanged, the sensor will look the same.
The API servers won't have newer data than the latest data the car has sent.
The car will only upload data to API servers on specific events such as unlock, lock, start charging, stop charging, set interval during charging etc.
If you want latest data, use the force refresh which will try to wake up the car to have it send latest status.
Take your time to read the README.
