### ISSUE TITLE
skodaconnect does not show in Add Integration

### ISSUE THREAD

**Issue by BirgerKo** [lendy007/homeassistant-skodaconnect#118]
**Describe the bug**
Installed the Skoda Connect integration through HACS
Restarted Home Assistant
Then going to "Configuration-> Devices&Services -> Add Integration" and search for skodaconnect. 

Nothing is found. Also searched for skoda.

**Latest working release**
First try for me.

**Debug logs**
Ran setup with recommended debug logs:
This is the only line with  "skoda" in it:
2022-04-11 09:53:45 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration skodaconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Installation:**
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.4.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.9",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Oslo",
    "os_name": "Linux",
    "os_version": "5.10.103-v8",
    "supervisor": "2022.03.5",
    "host_os": "Home Assistant OS 7.6",
    "docker_version": "20.10.9",
    "chassis": "embedded",
    "run_as_root": true

   "skodaconnect": {
      "version": "v1.0.67",
      "requirements": [
        "skodaconnect>=1.1.19",
        "homeassistant>=2021.12.0"

**Additional context**
None

**Comment by Farfar** [comment]
> **Describe the bug** Installed the Skoda Connect integration through HACS Restarted Home Assistant Then going to "Configuration-> Devices&Services -> Add Integration" and search for skodaconnect.
> 
> Nothing is found. Also searched for skoda.
> 
> **Latest working release** First try for me.
> 
> **Debug logs** Ran setup with recommended debug logs: This is the only line with "skoda" in it: 2022-04-11 09:53:45 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration skodaconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 
> **Installation:** "home_assistant": { "installation_type": "Home Assistant OS", "version": "2022.4.1", "dev": false, "hassio": true, "virtualenv": false, "python_version": "3.9.9", "docker": true, "arch": "aarch64", "timezone": "Europe/Oslo", "os_name": "Linux", "os_version": "5.10.103-v8", "supervisor": "2022.03.5", "host_os": "Home Assistant OS 7.6", "docker_version": "20.10.9", "chassis": "embedded", "run_as_root": true
> 
> "skodaconnect": { "version": "v1.0.67", "requirements": [ "skodaconnect>=1.1.19", "homeassistant>=2021.12.0"
> 
> **Additional context** None

This might be because of browser cache. There has been multiple reports of issues like this on Discord and all have been solved by using another browser or clearing cache/site data.
