### ISSUE TITLE
Consumption stays in metric.

### ISSUE THREAD

**Issue by strickersuk** [lendy007/homeassistant-skodaconnect#121]
**Describe the bug**
When conversion to imperial is selected the consumption remains in l/100km, the value also changes, for example when I have metric selected the value is 7.3, when imperial it changes to 5?

**Latest working release**
New user, first usage.

**Installation:**
 - Hass OS 8.0

**Comment by Farfar** [comment]
A fix for invalid conversion is in the works. Will be included in next version

**Comment by Farfar** [comment]
> **Describe the bug** When conversion to imperial is selected the consumption remains in l/100km, the value also changes, for example when I have metric selected the value is 7.3, when imperial it changes to 5?
> 
> **Latest working release** New user, first usage.
> 
> **Installation:**
> 
> * Hass OS 8.0

Fix for this in 1.0.70 beta. Will publish as stable once tested thoroughly.
