### ISSUE TITLE
Missing entity value

### ISSUE THREAD

**Issue by Depechie** [lendy007/homeassistant-skodaconnect#123]
**Describe the bug**
Not sure since when, but currently some entities are no longer showing values. Is this a known issue?

For example the Combined range now gives NaN.
Last connected gives invalid time stamp.

**Comment by gpuccio87** [comment]
Same problem for me. "Combined range" is unavailable

**Comment by Farfar** [comment]
I see that combined range is unavailable for me as well, will look into it .
Last connected works fine here so should not be an issue with the integration I think. Maybe locale settings causing it?

**Comment by Depechie** [comment]
Could indeed be a locale thing, but used to work before ...

![image](https://user-images.githubusercontent.com/351693/175772174-9a90cf19-038e-4577-acbb-1d4a558fedd6.jpeg)

**Comment by loeffelpan** [comment]
> Could indeed be a locale thing, but used to work before ...
> 
> ![image](https://user-images.githubusercontent.com/351693/175772174-9a90cf19-038e-4577-acbb-1d4a558fedd6.jpeg)

This "invalid timestamp" issue isn related to the other one you've mentiones.
For timestamp issue see #113. I raised a pull request to fix this.

**Comment by Depechie** [comment]
Thx for the clarification @loeffelpan !!

**Comment by gpuccio87** [comment]
Any news?

**Comment by loeffelpan** [comment]
@Farfar is on vacations.
I took a look into it and it seens that the combined value is missing on the API response. I think we'll have to calculate the combined value from combustion and electric range.

I'll try to raise another PR during the weekend, so @Farfar can review it.

**Comment by loeffelpan** [comment]
Will be fixed as soon as @Farfar reviews my pull request (and acknowledge that it is ok).

**Comment by Depechie** [comment]
@loeffelpan seems something changed again? It was fixed, but now I got -1 again :/
