### ISSUE TITLE
Mileage missing (skoda supperb Vi)

### ISSUE THREAD

**Issue by jeroenvdd** [lendy007/homeassistant-skodaconnect#124]
Hi,
first of all: the integration works perfectly every variable seems to be syncing well for the past few months,

but (and i might be doing something wrong)

I can't seem to find the total mileage entity?
or could this be missing for some cars?

**Comment by AMajland** [comment]
I've two skodas supported - but only one of them has the mileage shown (2019 Kodiaq) but not the other (2020 Enyaq)

Can you the Superb mileage on https://www.skoda-connect.com/ ?

I have a lot less for my Enyaq than the older Kodiaq.

**Comment by Farfar** [comment]
> Hi, first of all: the integration works perfectly every variable seems to be syncing well for the past few months,
> 
> but (and i might be doing something wrong)
> 
> I can't seem to find the total mileage entity? or could this be missing for some cars?

Its named "odometer" and should be available for all but Enyaq right now.

**Comment by Farfar** [comment]
> Hi Farfar sorry, I was on a holliday, i don't have the entity odometer, should i remove and read to be sure?

If you have a Enyaq then the odometer feature isn't implemented yet IIRC. Don't know if it's available in the app.
