### ISSUE TITLE
implement some further implementation

### ISSUE THREAD

**Issue by ChristophCaina** [lendy007/homeassistant-skodaconnect#129]
Hi all,

I am trying the following adapter on ioBroker for getting some information for my Skoda Enyaq.
Basically, it still does support the same things as your integration - but it seems, that it can pull a few more information from the service...

ioBroker-Adapter
https://github.com/TA2k/ioBroker.vw-connect

Additional information which I could not find within the skoda-connect:
![grafik](https://user-images.githubusercontent.com/26391061/179984783-056ab09d-da15-4786-b29b-f721dbeb6cb6.png)

As far as I got from their forum, they are also working on getting options for SW Version 3.0 from VW working...
Maybe, this could also help in extending the usability of this library?

**Comment by Farfar** [comment]
Most probably! This info is most definitely already collected in the integration but not mapped to any variables yet.
If you can provide a full debug, with responses enabled in integration settings, I can make sure that it I collect the correct names from the API json response.

**Comment by Farfar** [comment]
Added "Car info" sensor with what I felt was usable information.
