### ISSUE TITLE
Cupra Connect

### ISSUE THREAD

**Issue by DrDEadGuy** [lendy007/homeassistant-skodaconnect#13]
Hi Lendy007

Could you make another fork for CupraConnect, im sure some also would love to see Seat Connect...

Thanks

Kim

**Comment by lendy007** [comment]
Sorry, no capabilities how to do that as I don’t have access to Seat system. I did solve my own issue with Kodiaq and now I don’t have time to help with even enhancing this Skoda plugin, all the work is now being done by @Farfar. But feel free to take this project and modify it for Seat, I would say it is matter of changing couple of api targets and maybe some formats...

**Comment by Farfar** [comment]
> Hi Lendy007
> 
> Could you make another fork for CupraConnect, im sure some also would love to see Seat Connect...
> 
> Thanks
> 
> Kim

See https://github.com/Farfar/homeassistant-seatconnect
