### ISSUE TITLE
Online Anti-Theft

### ISSUE THREAD

**Issue by Nomeboj** [lendy007/homeassistant-skodaconnect#132]
Hi.

When alarm is triggered inside car it is sending notification to Skoda app. Is it possible to implement this in ha-skodaconnect?

Kind regards.

**Comment by Farfar** [comment]
> 

Not at the moment no. That feature use a kind of subscription to a push service. Maybe it's possible to reverse engineer the device registration for subscription but I haven't had any luck and don't have the time to do it.
