### ISSUE TITLE
Climatisation time left Unavailable at startup

### ISSUE THREAD

**Issue by vBrolin** [lendy007/homeassistant-skodaconnect#133]
If the electric climatisation isn't running when HA is started, Climatisation time left will be grayed out and Unavailable until the heater is started.
Setting it to default to 0 if it's not available would resolve this.

**Comment by Farfar** [comment]
> 

The library should return 00:00 if climatisation isn't running. If the sensor is unavailable it might be that the specific API response attribute has changed and isn't numeric when the heater isn't running.
I'll see if I can find something that might work for next release.

**Comment by vBrolin** [comment]
Update, checked again, and it doesnt start working if I start the heater either.
To get it to work, I need to reload the integration while the heater is running, then it works.

**Comment by Farfar** [comment]
> Update, checked again, and it doesnt start working if I start the heater either. To get it to work, I need to reload the integration while the heater is running, then it works.

Ok, that should be enough to find the issue. Most probably it doesn't return the json from API when heater isn't running and the "sensor" isn't marked as supported.

**Comment by Farfar** [comment]
Should be fixed in latest release.
