### ISSUE TITLE
Remote lock-control is not supported

### ISSUE THREAD

**Issue by bckmrk** [lendy007/homeassistant-skodaconnect#136]
Hi, with the new version of the custom integration and software 3.0 in the car, I've gotten a lock-control in Home Assistant. However, Trying to use it generates this message in the logs... 

```
Logger: skodaconnect.dashboard
Source: custom_components/skodaconnect/lock.py:57
Integration: Skoda Connect ([documentation](https://github.com/lendy007/homeassistant-skodaconnect/blob/main/README.md), [issues](https://github.com/lendy007/homeassistant-skodaconnect/issues))
First occurred: 13:46:27 (2 occurrences)
Last logged: 13:46:31

Unlock failed: Remote lock/unlock is not supported.
```

If it's not supported, why is the lock exposed? :-D 

Best regards.

**Comment by Farfar** [comment]
Because the lock entity is based on the status of lock sensor and I didn't bother with adding a bunch of checks to not render it for Enyaq. Hopefully we will see remote lock/unlock capability there as well soon.
