### ISSUE TITLE
HTTP error 500 for fetching position

### ISSUE THREAD

**Issue by ChristophCaina** [lendy007/homeassistant-skodaconnect#137]
Enyaq with Software Version 3.0 

```
Logger: skodaconnect.connection
Source: runner.py:119
First occurred: 29. September 2022 um 00:20:16 (2054 occurrences)
Last logged: 10:32:55

Could not fetch position, HTTP status code: 500
```

I've also seen, that the Skoda App / Webapplication seems not able to fetch / show the position.
I am not sure, if this feature is already implemented available at all - or if it is related to a privacy setting?

**Comment by Farfar** [comment]
> Enyaq with Software Version 3.0
> 
> ```
> Logger: skodaconnect.connection
> Source: runner.py:119
> First occurred: 29. September 2022 um 00:20:16 (2054 occurrences)
> Last logged: 10:32:55
> 
> Could not fetch position, HTTP status code: 500
> ```
> 
> I've also seen, that the Skoda App / Webapplication seems not able to fetch / show the position. I am not sure, if this feature is already implemented available at all - or if it is related to a privacy setting?

You need 2 things: software version 3.0 for Enyaq and share your data (privacy settings).
Since I don't have an Enyaq I can't tell you how to change privacy settings in the car.

**Comment by ChristophCaina** [comment]
This is already solved.
Sorry for Not updating the issue :-(
