### ISSUE TITLE
lock/unlock is not supported - Enyaq iV (SW: 3.0)

### ISSUE THREAD

**Issue by ChristophCaina** [lendy007/homeassistant-skodaconnect#138]
Is the "lock.doors" supposed to unlock / lock the car doors?
It seems that we do get the response "not supported" - so the function seems not to be available for the Enyaq at all...
therefore, I think it can be disabled in the integration?
Enyaq - SW version 3.0

```
Logger: skodaconnect.dashboard
Source: custom_components/skodaconnect/lock.py:57
Integration: Skoda Connect (documentation, issues)
First occurred: 29. September 2022 um 00:55:08 (6 occurrences)
Last logged: 29. September 2022 um 14:56:14

Unlock failed: Remote lock/unlock is not supported.
```

**Comment by Farfar** [comment]
> 

Yes and no. It's there because it shares the same code as all other cars, where it works. I won't rewrite the code since lock/unlock will work in the future. When the logic is available from the API I will clean up so it doesn't show up for Enyaq cars where it's unavailable. But not before then.
