### ISSUE TITLE
Position of car not working

### ISSUE THREAD

**Issue by chrisrock1984** [lendy007/homeassistant-skodaconnect#14]
Since 2 updates, the position of the car is not received.
Tracker says: "absent"
Car moving is not available

Do I need to do something after updating?
Anything else works as it should.

**Comment by Farfar** [comment]
> Since 2 updates, the position of the car is not received.
> Tracker says: "absent"
> Car moving is not available
> 
> Do I need to do something after updating?
> Anything else works as it should.

Can you provide a debug log?
Sometimes the integration doesn't correctly detect that position is supported if the API endpoint is unavailable when it initializes. Same problem can occur if the car is moving when integration initializes.

You shouldn't need to do anything but make sure that your car hasn't changed name, or the device_tracker has changed somehow. Check known_devices.yaml for new/changed entries.
A correct known_devices.yaml entry should look something like this (exchange <VIN-number> for your own or car name):
```yaml
<VIN-number/Car-name>:
  name: <VIN-number/Car-name>
  mac:
  icon: mdi:car
  picture:
  track: true
```

**Comment by chrisrock1984** [comment]
Hi,
just checked the known_devices.yaml, as you suggested and yes, there was a second car entry with a different name.
The entities of this "device" are now working.
Why has the name changed? I did not change it intentionally.

Thank you very much for your help!!

BR

**Comment by Farfar** [comment]
> Hi,
> just checked the known_devices.yaml, as you suggested and yes, there was a second car entry with a different name.
> The entities of this "device" are now working.
> Why has the name changed? I did not change it intentionally.
> 
> Thank you very much for your help!!
> 
> BR

It depends.
If you have a VIN-to-Name config in configuration.yaml and it is unchanged then it shouldn't have a new name.
If you hadn't set a name for your car, there's a change in code a while back where the integration picks up on the nickname set in the app/portal.
