### ISSUE TITLE
Latitude/Longitude information very infrequent

### ISSUE THREAD

**Issue by eili77** [lendy007/homeassistant-skodaconnect#141]
Hi,
to me, it looks like that attributes with GPS information (latitude + longitude) are updated very infrequently.
It looks like that it correlates value changes of the entity "device_tracker.position" (please see the following screenshot).

![image](https://user-images.githubusercontent.com/78401392/195978791-5a74c3b4-db88-461d-b4c7-f74b66ff4e43.png)

Is there a way to get/extract more requent GPS information?

Thanks all!

**Comment by jd1** [comment]
I don't know how the API handles the data, but at least in the app they the location of the vehicle is only available if it is parked.
Did you drive the vehicle when the status was unknown?

**Comment by eili77** [comment]
@jd1 Yes, 
"Unknown" = driving
"Away" = parking

**Comment by Farfar** [comment]
This is per design. The car does not update position while driving.
