### ISSUE TITLE
Changing charging option

### ISSUE THREAD

**Issue by are0002** [lendy007/homeassistant-skodaconnect#143]
feature request:
Select or change the charging options: "charging on preferred hours", "charging before departure time", "charge immediately"...

This option make's easy to manage the charge by scripting

**Comment by ChristophCaina** [comment]
for which car should this option be?
If it is for the Enyaq, I am not sure, if the App does provide this feature (at least, I haven't found it yet)...

Anyway - I think, that can be done with some simple automations and triggers - that activates the "charge" button when your conditions met.

**Comment by Farfar** [comment]
> feature request: Select or change the charging options: "charging on preferred hours", "charging before departure time", "charge immediately"...
> 
> This option make's easy to manage the charge by scripting

Off hours can be set via service call for departure timer.
Scheduled departure can include charging and/or climatisation.
There's a button for immediate charging.
