### ISSUE TITLE
Retrying setup: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by ChristophCaina** [lendy007/homeassistant-skodaconnect#149]
**Describe the bug**
Today I noticed the following error:
Retrying setup: 'NoneType' object has no attribute 'get'
![grafik](https://user-images.githubusercontent.com/26391061/202673326-0ffbad16-b39e-4ddf-87e4-76a0b08d4ad0.png)

```
Logger: homeassistant.config_entries
Source: config_entries.py:1089
First occurred: 10:49:29 AM (3 occurrences)
Last logged: 10:50:09 AM

Config entry '*******' for skodaconnect integration not ready yet: 'NoneType' object has no attribute 'get'; Retrying in background
```

```
Logger: skodaconnect.connection
Source: custom_components/skodaconnect/__init__.py:801
Integration: Skoda Connect ([documentation](https://github.com/lendy007/homeassistant-skodaconnect/blob/main/README.md), [issues](https://github.com/lendy007/homeassistant-skodaconnect/issues))
First occurred: 9:45:46 AM (21 occurrences)
Last logged: 10:50:56 AM
Received unhandled error indicating server-side problem. The service might be temporarily unavailable.
```

After checking the Skoda App, it appears, that the Servers from Skoda are offline at the moment.
This is also given in the second error message from the logs - but If this error can be fetched, it would be great, if this information can somehow be shown on the Integrations page - instead of an error that is "somehow" a "guess what they want to tell me" for average users.

**Latest working release**

**Debug logs**

**Installation:**
Hass OS 2011.11.03

**Additional context**
Confirmed downtime of the Skoda Servers, The Skoda app itself is also not working.

**Comment by Farfar** [comment]
See #151

**Comment by mydliar** [comment]
Had the same issue this morning, fixed it by logging into the Skoda app and accepting the terms and conditions on the firso screen.
