### ISSUE TITLE
service_inspection_km Not working

### ISSUE THREAD

**Issue by maccan-tech** [lendy007/homeassistant-skodaconnect#15]
Hi.
I have a Citygo e iV.
After version 1.0.24 i think it was the service_inspection_km only shows _unavailable_ in HA.

**Comment by Farfar** [comment]
> Hi.
> I have a Citygo e iV.
> After version 1.0.24 i think it was the service_inspection_km only shows _unavailable_ in HA.

The sensor has changed name to service_inspection_distance.

**Comment by maccan-tech** [comment]
I have tied that.
I get this message in HA then.
Running the latest skodaconnect (__version__ = "1.0.36")

`Invalid config for [skodaconnect]: value must be one of ['adblue_level', 'auxiliary_climatisation', 'battery_level', 'charge_max_ampere', 'charging', 'charging_cable_connected', 'charging_cable_locked', 'charging_time_left', 'climatisation_target_temperature', 'climatisation_without_external_power', 'combined_range', 'combustion_range', 'distance', 'door_closed_left_back', 'door_closed_left_front', 'door_closed_right_back', 'door_closed_right_front', 'door_locked', 'electric_climatisation', 'electric_range', 'energy_flow', 'external_power', 'fuel_level', 'hood_closed', 'last_connected', 'oil_inspection', 'oil_inspection_km', 'outside_temperature', 'parking_light', 'pheater_duration', 'pheater_heating', 'pheater_status', 'pheater_ventilation', 'position', 'request_in_progress', 'request_results', 'requests_remaining', 'service_inspection', 'service_inspection_km', 'sunroof_closed', 'trip_last_average_electric_consumption', 'trip_last_average_fuel_consumption', 'trip_last_average_speed', 'trip_last_duration', 'trip_last_length', 'trunk_closed', 'trunk_locked', 'window_closed_left_back', 'window_closed_left_front', 'window_closed_right_back', 'window_closed_right_front', 'window_heater', 'windows_closed'] @ data['skodaconnect']['resources'][20]. Got 'service_inspection_distance'. (See ?, line ?).`

**Comment by Farfar** [comment]
> @Farfar I have tied that.
> I get this message in HA then.
> Running the latest skodaconnect (**version** = "1.0.36")
> 
> `Invalid config for [skodaconnect]: value must be one of ['adblue_level', 'auxiliary_climatisation', 'battery_level', 'charge_max_ampere', 'charging', 'charging_cable_connected', 'charging_cable_locked', 'charging_time_left', 'climatisation_target_temperature', 'climatisation_without_external_power', 'combined_range', 'combustion_range', 'distance', 'door_closed_left_back', 'door_closed_left_front', 'door_closed_right_back', 'door_closed_right_front', 'door_locked', 'electric_climatisation', 'electric_range', 'energy_flow', 'external_power', 'fuel_level', 'hood_closed', 'last_connected', 'oil_inspection', 'oil_inspection_km', 'outside_temperature', 'parking_light', 'pheater_duration', 'pheater_heating', 'pheater_status', 'pheater_ventilation', 'position', 'request_in_progress', 'request_results', 'requests_remaining', 'service_inspection', 'service_inspection_km', 'sunroof_closed', 'trip_last_average_electric_consumption', 'trip_last_average_fuel_consumption', 'trip_last_average_speed', 'trip_last_duration', 'trip_last_length', 'trunk_closed', 'trunk_locked', 'window_closed_left_back', 'window_closed_left_front', 'window_closed_right_back', 'window_closed_right_front', 'window_heater', 'windows_closed'] @ data['skodaconnect']['resources'][20]. Got 'service_inspection_distance'. (See ?, line ?).`

Yes I can see now that the "resources" variable have the wrong names, will update for next release.
Quick question though, is there any specific reason as to why you specify resources? Do you want to exclude some entity from being created in HA?
Else I suggest you read the README, if you omit the 'resources:' config option everything that is supported will be created.

**Comment by maccan-tech** [comment]
Yes i want to exclude some entity, i am not interested in every entity.

**Comment by Farfar** [comment]
Fix is in latest commit, will be incorporated in next release.
