### ISSUE TITLE
has Skoda disabled Sensors for the Enyaq?

### ISSUE THREAD

**Issue by ChristophCaina** [lendy007/homeassistant-skodaconnect#150]
I recently noticed, that several of the Sensors the Skoda Integration did provide for my Enyaq have switched to "unavailable".
Reloading the integration, as well as restarting HA seems not to help...

Not all Sensors that came with the Upgrade of the Integration to support the 3.0 Software from the Enyaq gone unavailable... 

![grafik](https://user-images.githubusercontent.com/26391061/205245631-bba66d60-f570-4fc0-ab04-be2018e10f9e.png)
![grafik](https://user-images.githubusercontent.com/26391061/205245576-841f5e4b-2ea0-4924-94e8-938ac79bf368.png)
![grafik](https://user-images.githubusercontent.com/26391061/205245598-339db0ea-5748-4723-acf6-fc9e86d93ec1.png)

**Comment by ChristophCaina** [comment]
OK, it appears that the data can't be displayed within the Skoda MyConnect Website.
So probably - they have (again) issues with their online services...

**Comment by Farfar** [comment]
Yes I should add as troubleshooting step: check online Skoda connect and app

**Comment by ChristophCaina** [comment]
Hi @Farfar,
I tried some more things... it appears, that while even the Skoda app / Skoda Webpage seems to have some issues with showing the information, they are still available on their system.

But - the Skoda integration does not...
The sensors are not available for a long time now... and I am not sure, if Skoda has maybe changed something on their API which needs to be changed in the integration to get the information again.

Disabled values are:

Parking Lights,
Last online,
Windows and Door status
Odometer
the departure timers, ...

Within the logs, I am getting the following errors:

```
 Logger: skodaconnect.connection
Source: runner.py:119
First occurred: 1. Dezember 2022 um 13:09:13 (705 occurrences)
Last logged: 09:38:20

    Could not fetch position, HTTP status code: 403
    Could not fetch timers, HTTP status code: 500
    Could not fetch air-conditioning data, HTTP status code: 500
    Could not fetch position, HTTP status code: 500
    Could not fetch charging, error: 'coroutine' object has no attribute 'get'
```

So yes, it appears to be a server issue with Skoda... or?

**Comment by JanDetrez** [comment]
I have the same issue with my Enyaq. I have the suspicion this is related to some of the subscriptions of MySkoda running out and not being renewed by me. Did you fix this?

**Comment by JanDetrez** [comment]
> I have the same issue with my Enyaq. I have the suspicion this is related to some of the subscriptions of MySkoda running out and not being renewed by me. Oddly I still see the mileage in the MySkoda app. Did you fix this?

This seemed to have resolved itself recently, unclear what changed to me.
