### ISSUE TITLE
Images not showing on default entities card

### ISSUE THREAD

**Issue by craggus2000** [lendy007/homeassistant-skodaconnect#154]
Just installed the latest version, first time user. Images of the car are not showing on the card in my default dashboard. Please advise? See attached screenshot. Running latest version of HA 2022.12.0

![Capture](https://user-images.githubusercontent.com/6427359/206511902-88b3176e-adab-4644-a24f-0566f0b1f51a.JPG)

**Comment by Farfar** [comment]
This is not a support channel for how to use home assistant.
The URLs points to the images of your car. The integration does not provide any type of card or image by itself (other than the icon for device tracker).
Take a look at picture entity card in Home Assistant.
