### ISSUE TITLE
Images not showing on Default card

### ISSUE THREAD

**Issue by craggus2000** [lendy007/homeassistant-skodaconnect#155]
***Please note, this applies to the default card that was created automatically on the default HA dashboard - I did not create it - therefore I am re requesting this issue be looked at. And am happy to provide any more information as requested.

Just installed the latest version, first time user. Images of the car are not showing on the card in my default dashboard. Please advise? See attached screenshot. Running latest version of HA 2022.12.0

![Capture](https://user-images.githubusercontent.com/6427359/206663148-c0110c4c-de0b-4899-bcd7-7c2121797cdf.JPG)

**Comment by craggus2000** [comment]
Additional screenshots as example...
![capture1](https://user-images.githubusercontent.com/6427359/206677663-3010ba3f-755d-4fdd-87bc-a207792b6d85.JPG)
![capture2](https://user-images.githubusercontent.com/6427359/206677667-0ddb172e-95fe-48bf-9d41-c2466e64f433.JPG)

**Comment by Farfar** [comment]
This is not an issue with the integration. The integration does not create a card, Home Assistant does.
