### ISSUE TITLE
change mdi Icons to car-door and car-door-lock

### ISSUE THREAD

**Issue by ChristophCaina** [lendy007/homeassistant-skodaconnect#156]
**Is your feature request related to a problem? Please describe.**
with the release of 2022.12 the HA team has implemented different state colors for entities and binary sensors.

![grafik](https://user-images.githubusercontent.com/26391061/206711604-9102123d-0423-4702-b604-755492641b50.png)
This is the UI while using the entities:

```
type: entities
entities:
  - entity: binary_sensor.t******5_doors_locked
  - entity: lock.t*****5_door_locked
 ```
 
 I think, the default Icon (for both Entities) is mdi:lock
![grafik](https://user-images.githubusercontent.com/26391061/206712283-62b317a2-da1e-4842-8386-6699d6103299.png)

But I think, the icon: mdi:car-door and mdi:car-door-lock would be nicer for both, the binary sensor as well as the "lock" entity
![grafik](https://user-images.githubusercontent.com/26391061/206712205-965cd4f6-8f9b-43d6-a31b-68fd45bb78a2.png)

**Describe the solution you'd like**
cahnging the default icons for "lock" and "binary sensor. door lock" to the mdi:car-door and car-door-lock icons

**Describe alternatives you've considered**
can be done by template or Icon change in the UI - but would not reflect an Icon change depending on the current state

**Additional context**

**Comment by Farfar** [comment]
Implemented in latest release. Thanks for suggestion 😃
