### ISSUE TITLE
Model image for Cupra Formentor 2.0

### ISSUE THREAD

**Issue by AcidAces** [lendy007/homeassistant-skodaconnect#162]
Hi, model image for cupra formentor 2.0 is just a white silhouette of a car
![new-w1080](https://user-images.githubusercontent.com/110767220/210572609-cce5992a-6161-406b-adfe-c4254a5ee806.png)

**Comment by RamonQu** [comment]
You are using the Skoda Connect integration for a Cupra Car. The Volkswagen Audi group uses the same “connected”-infrastructure for most of their brands. But some elements may differ. So probably some elements wil work, but some not. You cannot expect a Cupra image from an Skoda-server ;)

So I think it’s better that somebody creates a Cupra-Fork. Please join the conversation on https://community.home-assistant.io/t/how-to-integrate-my-cupra-born/410996/18

**Comment by Farfar** [comment]
> You are using the Skoda Connect integration for a Cupra Car. The Volkswagen Audi group uses the same “connected”-infrastructure for most of their brands. But some elements may differ. So probably some elements wil work, but some not. You cannot expect a Cupra image from an Skoda-server ;)
> 
> So I think it’s better that somebody creates a Cupra-Fork. Please join the conversation on https://community.home-assistant.io/t/how-to-integrate-my-cupra-born/410996/18

There is a Cupra fork already, by me, but not maintained since I don't have a Seat myself.
For Skoda the secret required for fetching the model image url was a bit tricky to acquire, required tracing methods and checking variable values in code during runtime.
I imagine you need to do the same for Seat.
An easier way is to login to web portal and save that image or url.

**Comment by AcidAces** [comment]
> 

I tried changing the URL in the sensors in the states tab in developer tools, but it keeps changing back after a few seconds..
And sorry, I'm pretty new to home assistant

**Comment by AcidAces** [comment]
Sorry I'm pretty new to stuff like this, so if I just want to change the URL for the sensors and device tracker, how would i go about doing that?
I looked through the files in file editor, but can't seem to locate the url anywhere.

**Comment by Farfar** [comment]
> Sorry I'm pretty new to stuff like this, so if I just want to change the URL for the sensors and device tracker, how would i go about doing that? I looked through the files in file editor, but can't seem to locate the url anywhere.

Check out [Customize Entities](https://www.home-assistant.io/docs/configuration/customizing-devices/) 

You can add entity_picture to your device_tracker entity through customize.yaml.
Download a picture and put into the www folder under homeassistant on disk. Then reference it as 'local/picture.png'

**Comment by AcidAces** [comment]
> > Sorry I'm pretty new to stuff like this, so if I just want to change the URL for the sensors and device tracker, how would i go about doing that? I looked through the files in file editor, but can't seem to locate the url anywhere.
> 
> Check out [Customize Entities](https://www.home-assistant.io/docs/configuration/customizing-devices/)
> 
> You can add entity_picture to your device_tracker entity through customize.yaml. Download a picture and put into the www folder under homeassistant on disk. Then reference it as 'local/picture.png'

Thank you, that worked perfectly :)
