### ISSUE TITLE
Setting car charging max current

### ISSUE THREAD

**Issue by fursov** [lendy007/homeassistant-skodaconnect#166]
**Is your feature request related to a problem? Please describe.**
I would like to ask for a feature to set the charging max current through HA

**Describe the solution you'd like**
Instead of read-only sensor there could be an entity, through which current could be set (in my case (Skoda iV Superb) Maximum/Reduced is enough, but probably some other cars need also numeric values).

**Additional context**
The charger that comes with my Skoda iV Superb does not handle "Maximum" setting and I always need to switch to "Reduced" through dashboard or app. I'd like to build the automation which can automatically set the max charging current based on the car location (since I know that if I charge in certain location, I'll use car charger, not any other charge station).
I tried to use set_charger_current() from the scodaconnect library and it works nicely so backend functionality exists.
Thank you.

**Comment by Farfar** [comment]
This feature is already available through a service call:
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/1235384/211057307-735296e4-0069-43eb-8273-d3eedda285bd.png">

A switch has been requested enough times now though so I will implement it.

**Comment by Farfar** [comment]
Since you have a Superb iV you can set charging current to any value from 1-16 that you'd like through the service call. A switch will be maximum/reduced only (16/6)

**Comment by fursov** [comment]
Great! Thanks a lot for the hint!
