### ISSUE TITLE
Request: geocoded_location

### ISSUE THREAD

**Issue by Sha-Darim** [lendy007/homeassistant-skodaconnect#17]
Hi!

I would like to see the sensor.[car]_geocoded_location as part of the plugin. It would seem to be a possible , all nessesary data is present.

Keep up the good work!

**Comment by Farfar** [comment]
I'm not sure that this will get incorporated into the code since there's already 3rd party solutions that does this better.

**Comment by Sha-Darim** [comment]
Hm, I thought this was a part of Hass core - to be able to convert lat/lan to address. I have this for the phones I have in Hass allready.

**Comment by Farfar** [comment]
> Hm, I thought this was a part of Hass core - to be able to convert lat/lan to address. I have this for the phones I have in Hass allready.

AFAIK it's the companion app that reports this to Home Assistant.
