### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by laurenshoogendijk** [lendy007/homeassistant-skodaconnect#170]
{{ states.sensor.xxxxxx_model_image_url_large.state|string }} does not return any image URL anymore:

![image](https://user-images.githubusercontent.com/30146192/211808074-9e766275-1786-4693-bf8c-801f0034b85b.png)

**Comment by Farfar** [comment]
> {{ states.sensor.xxxxxx_model_image_url_large.state|string }} does not return any image URL anymore:
> 
> ![image](https://user-images.githubusercontent.com/30146192/211808074-9e766275-1786-4693-bf8c-801f0034b85b.png)

Working fine for me. Have you tried restarting integration?

**Comment by laurenshoogendijk** [comment]
> > {{ states.sensor.xxxxxx_model_image_url_large.state|string }} does not return any image URL anymore:
> > ![image](https://user-images.githubusercontent.com/30146192/211808074-9e766275-1786-4693-bf8c-801f0034b85b.png)
> 
> Working fine for me. Have you tried restarting integration?

I did try restarting, which did not work. The image however is loading again now, maybe a weird glitch in the matrix.
