### ISSUE TITLE
Login failed with error: Expected HTML data for initial login form!

### ISSUE THREAD

**Issue by timg83** [lendy007/homeassistant-skodaconnect#174]
First off, thanks so much for this great integration! It is much faster than using the Skoda App. Appreciate your work!

Since today I'm unable to interact using the SkodaConnect HA plugin. The integration could not be loaded due to a login error.

Logger: custom_components.skodaconnect.config_flow
Source: custom_components/skodaconnect/config_flow.py:103
Integration: Skoda Connect (documentation, issues)
First occurred: 20:36:51 (2 occurrences)
Last logged: 20:37:30

Login failed with error: Expected HTML data for initial login form!

I noticed today that I had to re-login on the My Skoda app also. Maybe this has to do with each other?

**Comment by Farfar** [comment]
> First off, thanks so much for this great integration! It is much faster than using the Skoda App. Appreciate your work!
> 
> Since today I'm unable to interact using the SkodaConnect HA plugin. The integration could not be loaded due to a login error.
> 
> Logger: custom_components.skodaconnect.config_flow Source: custom_components/skodaconnect/config_flow.py:103 Integration: Skoda Connect (documentation, issues) First occurred: 20:36:51 (2 occurrences) Last logged: 20:37:30
> 
> Login failed with error: Expected HTML data for initial login form!
> 
> I noticed today that I had to re-login on the My Skoda app also. Maybe this has to do with each other?

Update integration and also give consent to the new permissions in app and all should be working again.
