### ISSUE TITLE
None has no attribute get

### ISSUE THREAD

**Issue by cob94440** [lendy007/homeassistant-skodaconnect#175]
Hello, I had an update to latest integration version today. When i did that, i get that error. I tried to get back to 1.21 which was previously working without success.
I uninstalled integration and reinstall. now it ask for logon then it says just error.

**Comment by Farfar** [comment]
> Hello, I had an update to latest integration version today. When i did that, i get that error. I tried to get back to 1.21 which was previously working without success. I uninstalled integration and reinstall. now it ask for logon then it says just error.

First step in troubleshooting is trying the app.
There's apparently new consent needed since yesterday.
