### ISSUE TITLE
Login error after new release

### ISSUE THREAD

**Issue by dailybits** [lendy007/homeassistant-skodaconnect#176]
Updated to new release and had an errorcode during initialization.

_
Logger: custom_components.skodaconnect.config_flow
Source: custom_components/skodaconnect/config_flow.py:117
Integration: Skoda Connect ([documentation](https://github.com/lendy007/homeassistant-skodaconnect/blob/main/README.md), [issues](https://github.com/lendy007/homeassistant-skodaconnect/issues))
First occurred: 12:00:04 PM (3 occurrences)
Last logged: 12:23:02 PM

Fetch vehicles failed with error: 'NoneType' object has no attribute 'get'

_

Removed the integration and added it again. When logging in I get now an empty errorbox (in the "Loading next step for Skoda Connect" stage).

![image](https://user-images.githubusercontent.com/7830482/212469596-0aa476f3-d604-4336-a8d0-9fa85f6162dc.png)

Latest Home Assistant release and latest integration release.
 I can connect into Skoda Connect portal with same credentials (Skoda Enyaq).

**Comment by Farfar** [comment]
> Updated to new release and had an errorcode during initialization.
> 
> _ Logger: custom_components.skodaconnect.config_flow Source: custom_components/skodaconnect/config_flow.py:117 Integration: Skoda Connect ([documentation](https://github.com/lendy007/homeassistant-skodaconnect/blob/main/README.md), [issues](https://github.com/lendy007/homeassistant-skodaconnect/issues)) First occurred: 12:00:04 PM (3 occurrences) Last logged: 12:23:02 PM
> 
> Fetch vehicles failed with error: 'NoneType' object has no attribute 'get'
> 
> _
> 
> Removed the integration and added it again. When logging in I get now an empty errorbox (in the "Loading next step for Skoda Connect" stage).
> 
> ![image](https://user-images.githubusercontent.com/7830482/212469596-0aa476f3-d604-4336-a8d0-9fa85f6162dc.png)
> 
> Latest Home Assistant release and latest integration release. I can connect into Skoda Connect portal with same credentials (Skoda Enyaq).

Did you try with the app?
If you take some time to check closed issues there's a bunch with same issue that needed to accept new consent in app.

**Comment by dailybits** [comment]
Oeps. Sorry.

Indeed a new privacy policy that needs a new consent. 🙈
