### ISSUE TITLE
Updated from version 1.0.72 to current (1.2.3) - almost all sensors are missing

### ISSUE THREAD

**Issue by lucius-the** [lendy007/homeassistant-skodaconnect#177]
Updated from version 1.0.72 to version 1.2.3 and most sensors for my Kodiaq are gone.
No location sensor, no door/window sensors, almost everything is gone. I only have 6 sensors in total and none of them are useful (all of them are some URLs, nubmer of requests, etc).

I've deleted the integration and re-added, but no use.

**Comment by markblokpoel** [comment]
Not sure if I'm experiencing the same issue, but the whole integration doesn't load for me giving the following error message. I tried core-2022.12.4 and 2023.1.4.

`'NoneType' object has no attribute 'get'`

No error in the logs.

**Comment by markblokpoel** [comment]
Turn out, I needed to accept new terms and conditions and re-login into the myskoda app. then after reloading the integration it works again!

**Comment by ChristophCaina** [comment]
#176
#175 
#174 
#169 

@Farfar : would it be possible to throw a more specific error message if you need to accept the terms and conditions / give consent within the app?
I think that would help many others in such a case...

I wonder, if it would be possible to show a login screen / consent screen within the integration in order to set this directly within HA instead of using the APP

**Comment by Farfar** [comment]
> #176 #175 #174 #169
> 
> @Farfar : would it be possible to throw a more specific error message if you need to accept the terms and conditions / give consent within the app? I think that would help many others in such a case...
> 
> I wonder, if it would be possible to show a login screen / consent screen within the integration in order to set this directly within HA instead of using the APP

Of course it would be better to throw specific errors depending on what's wrong.
It's very difficult though to guess what VAG will change next and how it will affect code. Especially in a case such as this when it only seems to apply for a specific set of users (Enyaq) for which I have no way of testing/debugging.

**Comment by Farfar** [comment]
> I wonder, if it would be possible to show a login screen / consent screen within the integration in order to set this directly within HA instead of using the APP

I have thought about this and that's something I would like to implement. But since the EULA/consent changes are far between and noone actually sends me proper debugs when things like this happens it's more or less impossible.
I would need a complete trace of GET/POST from a client where new consent is required and that just won't happen.
And then I'm not even sure that a dynamic HTMl consent form is possible to implement in Home Assistant config flow.

**Comment by ChristophCaina** [comment]
hm... one of the main issues is in my opinion, that such failures remain un-noticed for some time - because you probably don't check the states of your car every hour... and even if you do - you probably don't check the state of the integration very regularely...

So, in most cases when I've seen this, the integration is throwing an error which is hard to understand for most people... it is just telling ``'NoneType' object has no attribute 'get'````- or something with an 500 error (that's when I usually starting checking the app)...

Would it be possible, to maybe throw a notification when the integration is receiving such a response 500 error?
Maybe, this could be added as an optional service or similar - just notifying the user "pls. check your skoda app" or something like that... ?

**Comment by Farfar** [comment]
> hm... one of the main issues is in my opinion, that such failures remain un-noticed for some time - because you probably don't check the states of your car every hour... and even if you do - you probably don't check the state of the integration very regularely...
> 
> So, in most cases when I've seen this, the integration is throwing an error which is hard to understand for most people... it is just telling ``'NoneType' object has no attribute 'get'````- or something with an 500 error (that's when I usually starting checking the app)...
> 
> Would it be possible, to maybe throw a notification when the integration is receiving such a response 500 error? Maybe, this could be added as an optional service or similar - just notifying the user "pls. check your skoda app" or something like that... ?

There's already errors for many problems that occurs. But since the servers aren't that reliable and I can't foresee every possible outcome it's a but difficult to actually code a relevant error every one that a user can understand and actually means something to me as a developer.

Most people won't even read the readme, where I've stated a few solutions, when they encounter problems. I often need debugs for problems that's actually related to the integration and not the servers. Perhaps 1/3 actually provides me with this.
Since I do this on my limited free time I focus on keeping up with VAG breaking changes and new features.

With all this said I'm rewriting the code to be more pep compliant and readable because I won't be actively maintaining this after Q2 2023 since I won't have a Skoda anymore.

**Comment by ChristophCaina** [comment]
Hi, thanks for the Update - and the Information about the topic with Code maintenance after Q2...
So you already have someone that could jump in with maintenance / Development?

If Not, I can see If I would be able to do at least some kind of maintenance

**Comment by rogerrally** [comment]
As per markblokpoel's comments, logging out of the Skoda Connect app on my phone and then re-logging in and accepting the T&C's sorted the 'NoneType' object has no attribute 'get' for me

**Comment by lucius-the** [comment]
Ok thanks everyone, so now I have pointers in the right direction. Logging in to Skoda app on mobile will most likely resolve the issue after I accept whatever terms are there again.

Kim: is there any way I can help at his moment ? Turn on debugging, send some logs ? Before I accept the new terms and resolve the issue for myself.

**Comment by lucius-the** [comment]
Guys... The reason this is not working for me is because my Škoda connect license has expired. Just remembered I got some email notification about the expiring licence and didn't pay for Škoda connect :(
sorry for the mess...
I'll see if I can get it for a normal price, since I didn't pay on time...

**Comment by lucius-the** [comment]
Yeah... Paying the subscription and then realoding the Škoda connect shows 46 sensors now. My bad. Closing the issue.

**Comment by Farfar** [comment]
> Guys... The reason this is not working for me is because my Škoda connect license has expired. Just remembered I got some email notification about the expiring licence and didn't pay for Škoda connect :( sorry for the mess... I'll see if I can get it for a normal price, since I didn't pay on time...

If the license expired there should have been a log entry saying so on startup of the integration. Which is one of the reasons I require logs :)

**Comment by lucius-the** [comment]
Yeah... I was looking at the logs from HA after installation, as I always do, but they were clean.
Do I need to turn on some additional logging to see warnings and errors from this component ?

**Comment by Farfar** [comment]
> Yeah... I was looking at the logs from HA after installation, as I always do, but they were clean. Do I need to turn on some additional logging to see warnings and errors from this component ?

It depends on what log level you have configured as default in home assistant. Default they only show warnings and errors unless you load full logs. And then it depends on your configuration.

**Comment by lucius-the** [comment]
Hm. Now I'm not getting location. It also says that the vehicle is moving, but it's parked since noon.
Seeing this in HA logs now:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/skodaconnect/switch.py:57
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 04:22:20 (1 occurrences)
Last logged: 04:22:20

[140017068882048] Data refresh is not supported.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/skodaconnect/switch.py", line 57, in async_turn_on
    await self.instrument.turn_on()
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 466, in turn_on
    await self.vehicle.set_refresh()
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 1269, in set_refresh
    raise SkodaInvalidRequestException('Data refresh is not supported.')
skodaconnect.exceptions.SkodaInvalidRequestException: Data refresh is not supported.
```

Will try to remove and re-add the integration.

**Comment by Farfar** [comment]
> Hm. Now I'm not getting location. It also says that the vehicle is moving, but it's parked since noon. Seeing this in HA logs now:
> 
> ```
> Logger: homeassistant.components.websocket_api.http.connection
> Source: custom_components/skodaconnect/switch.py:57
> Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
> First occurred: 04:22:20 (1 occurrences)
> Last logged: 04:22:20
> 
> [140017068882048] Data refresh is not supported.
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
>     await hass.services.async_call(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
>     await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
>     await service.entity_service_call(
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
>     future.result()  # pop exception if have
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
>     await coro
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
>     await result
>   File "/config/custom_components/skodaconnect/switch.py", line 57, in async_turn_on
>     await self.instrument.turn_on()
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 466, in turn_on
>     await self.vehicle.set_refresh()
>   File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 1269, in set_refresh
>     raise SkodaInvalidRequestException('Data refresh is not supported.')
> skodaconnect.exceptions.SkodaInvalidRequestException: Data refresh is not supported.
> ```
> 
> Will try to remove and re-add the integration.

Give it some time. You might need to force a refresh since the car has been without license for a while. Restart the integration or home assistant after next time you have driven the car. And make sure to check the privacy settings in car so they haven't reset to something restrictive. That will affect position status.

**Comment by lucius-the** [comment]
Nope, it's still the same. What I did:
- removed the integration
- restarted home assistant
- re-added the integration

Position is unkown. I tried a force refresh but got this again:
```
2023-01-15 03:22:20.732 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140017068882048] Data refresh is not supported.
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
await result
File "/config/custom_components/skodaconnect/switch.py", line 57, in async_turn_on
await self.instrument.turn_on()
File "/usr/local/lib/python3.10/site-packages/skodaconnect/dashboard.py", line 466, in turn_on
await self.vehicle.set_refresh()
File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 1269, in set_refresh
raise SkodaInvalidRequestException('Data refresh is not supported.')
skodaconnect.exceptions.SkodaInvalidRequestException: Data refresh is not supported.
```

Just seen your reply. Ok. I'll try to start the car, see if something pops up on the screen and try a refresh in a couple of hours. Many thanks for helping !

**Comment by lucius-the** [comment]
Staring the car and verifying that location sharing is still on. Also running the mobile app, logging in, confirming a few new options... finally turning the car off and after a couple of minutes position is shown in HA (and also in the mobile app, as it wasn't showing even there).

So, now it works again. Thank u !
