### ISSUE TITLE
Poll frequency in seconds or minutes

### ISSUE THREAD

**Issue by AdminOfThis** [lendy007/homeassistant-skodaconnect#183]
In the [README.md](https://github.com/lendy007/homeassistant-skodaconnect/blob/e816c28f28a773ee6a4fdd4071b01200c8435e9a/README.md), the polling frequency is described to be in minutes ("The interval (in minutes) that the servers are polled for updated data.")
However, in the configuration dialogue, the field for polling frequency says "Poll frequency (seconds)"), as seen in [strings.json](https://github.com/lendy007/homeassistant-skodaconnect/blob/a12e1be7673d5ecbc2763bf7526d105db10e57f0/custom_components/skodaconnect/strings.json).
Which one is correct?

(I know, this is a minor issue, but is confusing the shit out of me trying to get some semi up-to-date data)

**Comment by WebSpider** [comment]
This defaults to seconds, however there is a conversion option for minutes.

See https://github.com/lendy007/homeassistant-skodaconnect/blob/a12e1be7673d5ecbc2763bf7526d105db10e57f0/custom_components/skodaconnect/config_flow.py#L334 if you're interested in the code.

**Comment by Farfar** [comment]
Updated the readme to correctly state that it's seconds
