### ISSUE TITLE
Changing of the Unit_of_measurement does not work...

### ISSUE THREAD

**Issue by ChristophCaina** [lendy007/homeassistant-skodaconnect#185]
**Describe the bug**
with the recent HA versions, it is now possible to convert the unit of measurement of certain entities from type Energy / Power.

This Article describes some of the required changes for supporting this option:
https://developers.home-assistant.io/blog/2022/12/07/unit_system_changes/

Unfortunately, skodaconnect is appart of another one integration, where the option to convert the unit (charging power) is available in the entity settings, but after applying the change the unit of measurement remains the same.

I wanted to change the Charging_Rate from W to kW ... unfortunately, the Unit remains W.

on other integrations this feature was working as expected - therefore, I don't think that this is an issue with HA itself.

**Is this working in MySkoda app?***
no function of the Skoda App

**Latest working release**
none, since the change of unit of measurement (energy) was just added in January (or Februrary) and for Power with the March release.

**Debug logs**

**Installation:**
 - Hass OS
 - 
 - 

**Additional context**
https://developers.home-assistant.io/blog/2022/12/07/unit_system_changes/

**Comment by ChristophCaina** [comment]
seems to work nicely :)
Thanks!

**Comment by Farfar** [comment]
> seems to work nicely :) Thanks!
> 
> I thought, it might be related to the "unit of measurement vs. native_unit_of_measurement" ... but was pretty unsure, if it could directly changed... esle, I would have made a PR for this. Thanks!

Great!

**Comment by ChristophCaina** [comment]
Hi,
I need to reopen the ticket :)

The unit change itself does work, but the sensor value will not be changed... :-(
![grafik](https://user-images.githubusercontent.com/26391061/227714854-8fa068e0-9fd3-4092-8a48-14a63fa30df1.png)

it shows "5000 kW" instead of 5 kW
the value remains the same while changing between W and kW
Not sure, why this happens, but it seems a bit strange to me, because I thought, HA should handle how the value will be displayed...
