### ISSUE TITLE
Model image URL unavailable in HA

### ISSUE THREAD

**Issue by XalaTheShepard** [lendy007/homeassistant-skodaconnect#191]
Dear all, 

After a reboot of my HA installation on Thursday 27th of April, the model image URL (both large and small) are unavailable in HA. 
This causes the image of my Skoda car to be not loaded into HA. 

I receive this error message in the logs: 

Logger: skodaconnect.connection
Source: runner.py:179
First occurred: 11:37:34 AM (8 occurrences)
Last logged: 1:05:38 PM

Received unhandled error indicating client-side problem. Restart or try again later.
Could not fetch cyclic trip statistics, HTTP status code: 429
Could not fetch longterm trip statistics, HTTP status code: 429

**Comment by ChristophCaina** [comment]
same here. Model images are gone... :-(
But I don't think that the log you have shown are related to the issue with the images itself.

It's showing "cyclic trip statistics" and "longterm trip statistics" ...
HTTP Status 429 is "too many requests"...

I am getting the following error for the images:

```
Logger: homeassistant.components.generic.camera
Source: components/generic/camera.py:211
Integration: Generic Camera (documentation, issues)
First occurred: 28. April 2023 um 21:53:43 (768 occurrences)
Last logged: 10:37:38

Error getting new camera image from Skoda Enyaq: Request URL is missing an 'http://' or 'https://' protocol.
```

**Comment by dvx76** [comment]
Can confirm. I suspect the response from the API has changed slightly. I need to run now but here is what I found so far:

We're in https://github.com/skodaconnect/skodaconnect/blob/main/skodaconnect/connection.py#L1007-L1016

The response from that get is (at least now) the actual model image. We expect to find a `Location` header in the response, but it's not (no longer) there.

```
<ClientResponse(https://iaservices.skoda-auto.com/ms/GetMODCWPImage?vin=MYVIN&view=main&appId=ModcwpMobile&date=2023-04-29T09:04Z&sign=REDACTED%3D) [200 OK]>
<CIMultiDictProxy('Date': 'Sat, 29 Apr 2023 09:41:05 GMT', 'Content-Type': 'image/png', 'Content-Length': '256819', 'Connection': 'keep-alive', 'Accept-Ranges': 'bytes', 'Age': '130284', 'Cache-Control': 'public, max-age=2592000', 'Etag': '"0x8DA85BAA50B50CC"', 'Last-Modified': 'Wed, 24 Aug 2022 10:23:10 GMT', 'Request-Context': 'appId=cid-v1:bf826632-1c1d-43b9-a793-f1ce95549075', 'X-Cache': 'HIT', 'x-ms-blob-type': 'BlockBlob', 'x-ms-lease-state': 'available', 'x-ms-lease-status': 'unlocked', 'x-ms-request-id': 'aca3d2fe-c01e-0001-5b4f-79a10b000000', 'x-ms-version': '2014-02-14', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains')>
```

**Comment by XalaTheShepard** [comment]
After a reboot today, the issue seems to be solved. I have noticed that the Skoda Connect also had some changes, including new car model images, so it might have been due to an update of Skoda themselves.

**Comment by ChristophCaina** [comment]
Yes, appears to be fixedGesendet von Outlook für Android
