### ISSUE TITLE
Skoda Connect does not show up under Integrations

### ISSUE THREAD

**Issue by quantummobile** [lendy007/homeassistant-skodaconnect#21]
**Describe the bug**
Skoda Connect does not show up under Integrations after installed via HACS.

**Latest working release**
If the problem started after updating to a new release, please state latest working release.

**Debug logs**
If applicable, add debug logs. See [README](https://github.com/lendy007/homeassistant-skodaconnect#enable-debug-logging) on how to enable debug logs with response debugging.

**Installation:**
 - Home Assistant variant: [e.g. Hass OS, Docker, Core, Supervised]
Home Assistant OS 5.12
Supervisor-2021.02.11
Core-2021.2.3

 - Python version [e.g. 3.7, 3.8]
 - Python library versions ["python3 -m pip list"]

**Additional context**

**Comment by Farfar** [comment]
Read the README. There's no config flow for this integration so it won't show up under integrations.
