### ISSUE TITLE
You have reached the maximum number of the requests that can be sent.

### ISSUE THREAD

**Issue by miehar** [lendy007/homeassistant-skodaconnect#25]
Hi,
I'm polling my car data in 15min loop and store it into mysql which is the backend for my grafana. That seems to be too often because I get the following warning in my MySkoda app "You have reached the maximum number of the requests that can be sent.".  This warning does not show in Skoda Connect response only in my android app.
I didn't find any information what is the request limit per day for the API. Does anyone know ?

**Comment by Farfar** [comment]
> Hi,
> I'm polling my car data in 15min loop and store it into mysql which is the backend for my grafana. That seems to be too often because I get the following warning in my MySkoda app "You have reached the maximum number of the requests that can be sent.". This warning does not show in Skoda Connect response only in my android app.
> I didn't find any information what is the request limit per day for the API. Does anyone know ?

This has nothing to do with how often the API is polled for info.
However, if you force refresh (this is done when you start the app), it will count as a request. Maximum number of requests is 15, then you need to drive the car until the number is reser.
