### ISSUE TITLE
Periodic update sensor remaining_requests

### ISSUE THREAD

**Issue by loeffelpan** [lendy007/homeassistant-skodaconnect#26]
I have an automation running for charging depending on solar power, which consumps quite a lot of requests at some days. Sometimes 15 requests gone to 0.
In that cases I „reset“ the request by turning ignition on and off. But the integration seems not to update that sensor periodically and my automations are stuck, as I use the remaining request as a condition. For now I have to force an update via switch, which consumps one request for „nothing“.

Is the limitation to 15 request by your integration or is this by skodas service?
Could you either update that sensor as all the others?
Maybe you could force an update without consumping a request?

**Comment by Farfar** [comment]
> I have an automation running for charging depending on solar power, which consumps quite a lot of requests at some days. Sometimes 15 requests gone to 0.
> In that cases I „reset“ the request by turning ignition on and off. But the integration seems not to update that sensor periodically and my automations are stuck, as I use the remaining request as a condition. For now I have to force an update via switch, which consumps one request for „nothing“.
> 
> Is the limitation to 15 request by your integration or is this by skodas service?
> Could you either update that sensor as all the others?
> Maybe you could force an update without consumping a request?

The limit is set by VW Group om server level, nothing I can get around in the integration I'm afraid.
I only know of one way to get the number of requests and that is by performing a request. The native app does some trickery to know this but I have not been able to regerar engineer it.

Since the number gets reset every time the car has been driven the integration cheats by resetting the number to 15 when it detects the car is moving. This is somewhat of a hack since it's a bit of hit and miss as you have noticed. If the car starts and stops between two polling cycles then the integration won't pick up in it and won't reset the number of requests.

**Comment by loeffelpan** [comment]
Thanks for explaination.
How do you detect that the car is moving? Turning ignition on and off seems to reset the requests on server side and last time I would bet the integration shows 15 requests remaining. Today I switches ignition on and offvery fast (within 20 seconds) which was maybe between two polling cycles.

Do you say that ignition on and off over two polling cycles will reset the requests due to the hack you‘ve mentioned? That would be a workaround for me.

**Comment by Farfar** [comment]
If the app triggers in the same way, only faster. Then keeping the ignition on for at least 1 polling cycle (what you defined in configuration.yaml).

I will see if there's another way to implement this as well. It probably involves keeping track of timestamp of last counter reset. Have you noticed of parking time timestamp is updated when you switch ignition on and off?

**Comment by loeffelpan** [comment]
Parkingtime seems to be not supported by my Superb iV.
Whatever it is not in the entity list.

**Comment by Farfar** [comment]
> Parkingtime seems to be not supported by my Superb iV.
> Whatever it is not in the entity list.

Strange, it should show up for all cars with device tracker

**Comment by loeffelpan** [comment]
Does this depend on privacy settings in the car.
I remember that i switched off some services.

**Comment by loeffelpan** [comment]
After changing privacy settings in the car the missing entities like „parking_time“ appeared.
And yes parking_time has changes on ignition on and off.

How do you detect movement for now?
Yesterday (after change of privacy settings) the reqests raise to 15 immediately with the next poll after ignition. Maybe your hack didn‘t work for me due to my privacy settings. And it does now?

**Comment by Farfar** [comment]
Yes most probably the privacy settings were hindering the reset.
The car still needs to be on over a polling cycle for the current implementation to detect it.
I might rewrite it to reset the number on parking time updated, that should be more reliable.

**Comment by loeffelpan** [comment]
Sounds fine.
Maybe the privacy setting are worth a hint in the readme, as „parking position“ has to be enabled for reliable reset of request.

I will get the updates version on hacs.
Thanks.

**Comment by Farfar** [comment]
Information regarding privacy settings has been added to README
