### ISSUE TITLE
Average fuel consumption sensor unavailable after latest update

### ISSUE THREAD

**Issue by quantummobile** [lendy007/homeassistant-skodaconnect#27]
**Describe the bug**

Average fuel consumption sensor unavailable after latest update

**Latest working release**
If the problem started after updating to a new release, please state latest working release.

**Debug logs**
If applicable, add debug logs. See [README](https://github.com/lendy007/homeassistant-skodaconnect#enable-debug-logging) on how to enable debug logs with response debugging.

**Installation:**
 - Home Assistant variant: [e.g. Hass OS, Docker, Core, Supervised]
 - Python version [e.g. 3.7, 3.8]
 - Python library versions ["python3 -m pip list"]

**Additional context**

**Comment by Farfar** [comment]
> Average fuel consumption sensor unavailable after latest update

This issue is quite lacking in information. What release is this not working in? In which release was it working?
The latest, 1.0.40-RC1 is purely a beta release for testing new API login and should not be used of you don't have any problem with 1.0.38.

**Comment by quantummobile** [comment]
The release this issue occured is v1.0.38.
There was no issue with average fuel consumption sensor in previous releases.

Home Assistant OS 5.12
core-2021.3.4
supervisor-2021.03.6

**Comment by Farfar** [comment]
> The release this issue occured is v1.0.38.
> There was no issue with average fuel consumption sensor in previous releases.
> 
> Home Assistant OS 5.12
> core-2021.3.4
> supervisor-2021.03.6

Can you please provide some debug logs?

**Comment by quantummobile** [comment]
Sure, but I need your guidance on this matter.

**Comment by Farfar** [comment]
> Sure, but I need your guidance on this matter.

Check the README [here](https://github.com/lendy007/homeassistant-skodaconnect#enable-debug-logging) on how to enable debug logging.

**Comment by quantummobile** [comment]
> > Sure, but I need your guidance on this matter.
> 
> Check the README [here](https://github.com/lendy007/homeassistant-skodaconnect#enable-debug-logging) on how to enable debug logging.

Thanks, I presume only this should be enabled?
custom_components.skodaconnect.sensor: debug

**Comment by Farfar** [comment]
> > > Sure, but I need your guidance on this matter.
> > 
> > 
> > Check the README [here](https://github.com/lendy007/homeassistant-skodaconnect#enable-debug-logging) on how to enable debug logging.
> 
> Thanks, I presume only this should be enabled?
> custom_components.skodaconnect.sensor: debug

For me to know what might go wrong I need you to enable: 'skodaconnect.connection: debug'
Also add 'response_debug: True' under skodaconnect configuration to enable logging of raw API responses, that might also help in debugging your issue.

**Comment by quantummobile** [comment]
Alright, looks like the issue was on the Skoda side. I did notice in the logs, that login to skodaconnect fails. Turned out that their own app experienced outages, must be some server related stuff.

After the Skoda app was fixed, I restarted HA and sensor is back to normal now.
