### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by danieljarhult** [lendy007/homeassistant-skodaconnect#29]
Hello, 
Since today after a reboot of my homeassitant i get the following errors;

**Could not login to Skoda Connect, please check your credentials and verify that the service is working
17:30:18 – skodaconnect (WARNING) - Meddelandet inträffade först 17:22:10 och har hänt 9 gånger

Login failed for skoda account, 'NoneType' object is not subscriptable
17:30:18 – /usr/local/lib/python3.8/site-packages/skodaconnect/connection.py (ERROR) - Meddelandet inträffade först 17:22:10 och har hänt 9 gånger

Setup failed for skodaconnect: Integration failed to initialize.
17:22:10 – setup.py (ERROR)**

App is working good, and this addon has been working perfect until today.

**Comment by supergroover** [comment]
When you go to the site [https://www.skoda-connect.com](https://www.skoda-connect.com) , you log in with your credentials and accept the terms and conditions it seems to work again.

**Comment by danieljarhult** [comment]
Ok, that was simple. It works again :) Thank you and have a nice week!
