### ISSUE TITLE
Can't connect to skoda new API

### ISSUE THREAD

**Issue by Nunak** [lendy007/homeassistant-skodaconnect#35]
**Describe the bug**
I did accept terms on https://www.skoda-connect.com/ . On 1.38 is just saying wrong credentials.
2021-05-24 11:37:27 WARNING (MainThread) [skodaconnect.connection] You need to login to Skoda Connect online and accept the terms and conditions.
2021-05-24 11:37:27 ERROR (MainThread) [skodaconnect.connection] Login failed for skoda account, the terms and conditions must be accepted
2021-05-24 11:37:27 WARNING (MainThread) [custom_components.skodaconnect] Could not login to Skoda Connect, please check your credentials and verify that the service is working

**Latest working release**
If the problem started after updating to a new release, please state latest working release. Everything stop working when skoda is acceted only on new API(skoda one).

**Debug logs**
If applicable, add debug logs. See [README](https://github.com/lendy007/homeassistant-skodaconnect#enable-debug-logging) on how to enable debug logs with response debugging.

**Installation:**
 - Home Assistant variant:  Core
 - Python version 3.9
 - Python library versions 
(11:38:24)(3.4G) [root@has-001:~] # python3 -m pip list
Package           Version
----------------- ---------
acme              0.31.0
apparmor          2.13.2
asn1crypto        0.24.0
beautifulsoup4    4.7.1
certbot           0.31.0
certbot-apache    0.31.0
certifi           2018.8.24
chardet           3.0.4
ConfigArgParse    0.13.0
configobj         5.0.6
cryptography      2.6.1
entrypoints       0.3
future            0.16.0
html5lib          1.0.1
idna              2.6
josepy            1.1.0
keyring           17.1.1
keyrings.alt      3.1.1
LibAppArmor       2.13.2
lxml              4.3.2
mock              2.0.0
parsedatetime     2.4
pbr               4.2.0
pip               18.1
pycrypto          2.6.1
pycurl            7.43.0.2
PyGObject         3.30.4
pyOpenSSL         19.0.0
pyRFC3339         1.1
python-apt        1.8.4.3
python-augeas     0.5.0
pytz              2019.1
pyxdg             0.25
requests          2.21.0
requests-toolbelt 0.8.0
SecretStorage     2.3.1
setuptools        40.8.0
six               1.12.0
soupsieve         1.8
urllib3           1.24.1
webencodings      0.5.1
wheel             0.32.3
zope.component    4.3.0
zope.event        4.2.0
zope.hookable     4.0.4
zope.interface    4.3.2

**Additional context**
My car is skoda superb 2018

**Comment by Farfar** [comment]
Which version are you using?
Also, the pip list command should be run as the user running homeassistant. If you are running in a python venv then activate venv and run again.

> Everything stop working when skoda is acceted only on new API(skoda one).
Did this ever work for you? AFAIK Skoda Superb is still on old API.
Does the MySkoda app work correctly?

**Comment by Nunak** [comment]
> Which version are you using?
Right now RC5. Was trying also 1.38.
> Also, the pip list command should be run as the user running homeassistant. If you are running in a python venv then activate venv and run again.
Sorry my bad now under correct user:
(homeassistant) homeassistant@has-001:~$ python3 -m pip list
Package                 Version
----------------------- ------------
acme                    1.8.0
adguardhome             0.3.0
aiocoap                 0.4b3
aioesphomeapi           2.6.3
aiofiles                0.5.0
aiogithubapi            2.0.0
aiohomekit              0.2.53
aiohttp                 3.6.2
aiohttp-cors            0.7.0
aioshelly               0.3.4
android-backup          0.2.0
appdirs                 1.4.3
asn1crypto              0.24.0
astral                  1.10.1
async-timeout           3.0.1
atomicwrites            1.4.0
attrs                   19.3.0
av                      6.1.2
backoff                 1.10.0
base36                  0.1.1
bcrypt                  3.1.7
beautifulsoup4          4.8.0
boto3                   1.12.24
botocore                1.15.24
brother                 0.1.14
cachetools              2.0.1
casttube                0.2.0
certifi                 2020.6.20
cffi                    1.12.3
chardet                 3.0.4
ciso8601                2.1.3
click                   7.1.2
coloredlogs             10.0
construct               2.9.45
croniter                0.3.34
cryptography            2.9.2
curve25519-donna        1.3
deepmerge               0.1.0
defusedxml              0.6.0
distro                  1.5.0
docopt                  0.6.2
docutils                0.14
ecdsa                   0.13.2
ed25519                 1.5
emoji                   0.5.4
enum-compat             0.0.2
envs                    1.3
flux-led                0.22
fnvhash                 0.1.0
future                  0.17.1
gTTS-token              1.1.3
ha-ffmpeg               2.0
hacs-frontend           202009091732
HAP-python              2.8.4
hass-nabucasa           0.37.0
hbmqtt                  0.9.5
hkdf                    0.0.3
home-assistant-frontend 20201001.2
homeassistant           0.116.4
homekit                 0.15.0
http-ece                1.1.0
httpsig                 1.3.0
humanfriendly           4.18
idna                    2.8
ifaddr                  0.1.7
importlib-metadata      1.6.0
influxdb                5.2.3
influxdb-client         1.8.0
integrationhelper       0.2.2
Jinja2                  2.11.2
jmespath                0.9.4
josepy                  1.1.0
jsonpath                0.82
librouteros             3.0.0
locationsharinglib      4.1.0
lxml                    4.5.0
MarkupSafe              1.1.1
midea-andersonshatch    0.1.11
mock                    3.0.5
multidict               4.5.2
mutagen                 1.45.1
mysqlclient             1.4.6
natsort                 7.0.1
netdisco                2.8.2
netifaces               0.10.9
numpy                   1.16.4
opencv-python-headless  4.1.0.25
openhomedevice          0.6.3
packaging               20.4
paho-mqtt               1.5.0
passlib                 1.7.1
Pillow                  7.2.0
pip                     20.2.3
pkg-resources           0.0.0
PlexAPI                 4.1.1
plexauth                0.0.5
plexwebsocket           0.0.12
ply                     3.11
protobuf                3.13.0
pushbullet.py           0.11.0
py-vapid                1.5.0
pyasn1                  0.4.8
PyChromecast            7.5.0
pycognito               0.1.4
pycparser               2.19
pycryptodome            3.9.6
pycryptodomex           3.9.4
pyfttt                  0.3
pyipp                   0.11.0
PyJWT                   1.7.1
PyMetno                 0.8.1
PyNaCl                  1.3.0
pynut2                  2.1.2
pyOpenSSL               19.0.0
pyotp                   2.3.0
pyparsing               2.4.7
pyps4-2ndscreen         1.1.1
PyQRCode                1.2.1
pyRFC3339               1.1
pyShelly                0.1.27
pysmartapp              0.3.2
pysmartthings           0.6.9
pysmi                   0.3.4
pysnmp                  4.4.12
pysonos                 0.0.33
python-dateutil         2.8.0
python-forecastio       1.4.0
python-jose             3.2.0
python-jose-cryptodome  1.3.2
python-magic            0.4.15
python-miio             0.5.3
python-mpd2             1.0.0
python-slugify          4.0.1
python-telnet-vlc       1.0.4
PyTurboJPEG             1.4.0
pytz                    2020.1
pywebpush               1.9.2
PyXiaomiGateway         0.13.3
PyYAML                  5.3.1
queueman                0.5
requests                2.24.0
requests-toolbelt       0.9.1
responses               0.10.6
RestrictedPython        5.0
rsa                     4.0
ruamel.yaml             0.15.100
Rx                      3.1.0
s3transfer              0.3.3
samsungctl              0.7.1
samsungtvws             1.4.0
semantic-version        2.8.5
setuptools              40.8.0
simplepush              1.1.4
six                     1.12.0
snitun                  0.20
soupsieve               1.9.4
speedtest-cli           2.1.2
spotipy                 2.16.0
spotipy-homeassistant   2.4.4.dev1
SQLAlchemy              1.3.19
text-unidecode          1.3
tlslite-ng              0.7.5
tqdm                    4.47.0
transitions             0.6.9
urllib3                 1.25.10
voluptuous              0.12.0
voluptuous-serialize    2.4.0
wakeonlan               1.1.6
waqiasync               1.0.0
warrant                 0.6.1
websocket-client        0.56.0
websockets              7.0
wheel                   0.34.2
wled                    0.4.4
xmltodict               0.12.0
yarl                    1.4.2
yeelight                0.5.4
zeroconf                0.28.5
zipp                    0.5.1
WARNING: You are using pip version 20.2.3; however, version 21.1.1 is available.
You should consider upgrading via the '/srv/homeassistant/bin/python3 -m pip install --upgrade pip' command.

> 
> > Everything stop working when skoda is acceted only on new API(skoda one).
> 
> Did this ever work for you? AFAIK Skoda Superb is still on old API.
Yes it was working for me.

> Does the MySkoda app work correctly?
Yes it's working for me fine.

**Comment by Farfar** [comment]
> (homeassistant) homeassistant@has-001:~$ python3 -m pip list

I can't see that the skodaconnect library is installed from that list? It should show up with the same version as the HASS component, 1.0.40rc5

**Comment by Nunak** [comment]
> I can't see that the skodaconnect library is installed from that list? It should show up with the same version as the HASS component, 1.0.40rc5

How is that possible ? I am using HACS.

**Comment by daranto** [comment]
Hello,
I have the same issue. The MySkoda App is working with my new Enyaq IV. But the custom component does not. Wrong credentials:

`Could not login to Skoda Connect, please check your credentials and verify that the service is working`

**Comment by rhoegen** [comment]
I had the same issue with the custom component and noticed that the skoda-connect.com Website did not recognize me accepting the new terms and conditions. Every time I logged out and in it wanted me to accept again. The solution for me was to delete all browser history/cookies and login again to the site, accepting the terms & conditions one final time.

**Comment by Farfar** [comment]
@daranto and @Farfar could you try what rhoegen suggested? Login to skoda connect web portal and make sure to accept terms and conditions. If you have done so already you can try in new browser.

**Comment by Nunak** [comment]
> I had the same issue with the custom component and noticed that the skoda-connect.com Website did not recognize me accepting the new terms and conditions. Every time I logged out and in it wanted me to accept again. The solution for me was to delete all browser history/cookies and login again to the site, accepting the terms & conditions one final time.

for me it was asking just one time. Now it's not asking me for accept, but integration is not working.

**Comment by Farfar** [comment]
> > I had the same issue with the custom component and noticed that the skoda-connect.com Website did not recognize me accepting the new terms and conditions. Every time I logged out and in it wanted me to accept again. The solution for me was to delete all browser history/cookies and login again to the site, accepting the terms & conditions one final time.
> 
> for me it was asking just one time. Now it's not asking me for accept, but integration is not working.

Do you still get the error from the integration that you need to accept the conditions? If so then try another web browser on skoda connect web portal.

**Comment by daranto** [comment]
seems to work now. But I did not change anything. Maybe the Skoda Service was unavailable, when I tried to configure the component.

**Comment by Farfar** [comment]
> hmmh that's strange. Firefox is not asking for accept, Chrome is not asking for accept, but Safari yes and every login.

Try to clear cache in Chrome/FF and see if you can accept T&C again.

**Comment by Farfar** [comment]
Since I haven't heard back I assume the issue was T&C

**Comment by Nunak** [comment]
Issue still exist :(

**Comment by Farfar** [comment]
> Issue still exist :(

Unforrunately I can't force anything. If the API redirects to EULA/T&C then it needs to be accepted and you need to do it on the site https://www.skoda-connect.com
If that doesn't "stick" then I'm afraid there's nothing I can do.
