### ISSUE TITLE
Seat Connect wont load on HA 2021.6

### ISSUE THREAD

**Issue by daunjo** [lendy007/homeassistant-skodaconnect#36]
**Describe the bug**
Seat Connect wont load on HA 2021.6 (no issue reporting on that fork so i hope this is ok?)

**Debug logs**
The custom integration 'seatconnect' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Additional context**
I think this is due to HA now demands an version manifest for third party integrations?

**Comment by EricDev06** [comment]
Yes you need to add a line in manifest.json :
"version": "v1.0.31"

**Comment by Farfar** [comment]
I'll take a look and will update manifest etc.

**Comment by Farfar** [comment]
> The custom integration 'seatconnect' does not have a valid version key (None) in the manifest file and was blocked from loading.

This is fixed in version 1.0.32, please update.
I have also added issues section to the github page.
