### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by topche** [lendy007/homeassistant-skodaconnect#40]
**Describe the bug**
The integration can't login into the Skoda portal

**Latest working release**
last release

**Debug logs**
Logger: skodaconnect.connection
Source: /usr/local/lib/python3.8/site-packages/skodaconnect/connection.py:283
First occurred: 12:04:07 PM (12 occurrences)
Last logged: 12:15:19 PM

Login failed for skoda account, 'NoneType' object is not subscriptable

**Installation:**
 - Home Assistant variant: Docker/Supervised
 - Python version 3.8
 - Python library versions ["long list"]

**Additional context**

**Comment by Farfar** [comment]
With "last release" is it latest stable or latest RC?
Try to login with your browser, does it work? Do you get any terms and conditions you need to accept?

**Comment by topche** [comment]
1.0.83
not 1.0.40-RC

**Comment by Farfar** [comment]
> 1.0.83
> not 1.0.40-RC
> yes, i did login via web and accept T&C

OK. Please verify with another browser as well. 90% of theese issues are because of updated T&C

**Comment by topche** [comment]
Hey ... that is strange .... 
now I have 

skodaconnect
skodaconnect.device_tracker
skodaconnect.lock
skodaconnect.switch
skodaconnect.sensor
skodaconnect.binary_sensor

**Comment by Farfar** [comment]
> Hey ... that is strange ....
> now I have
> 
> skodaconnect
> skodaconnect.device_tracker
> skodaconnect.lock
> skodaconnect.switch
> skodaconnect.sensor
> skodaconnect.binary_sensor

Please test latest release (1.0.42-RC1) if you still have issues. It's also rewritten for config flow.
