### ISSUE TITLE
Two accounts?

### ISSUE THREAD

**Issue by bruxy70** [lendy007/homeassistant-skodaconnect#50]
How do I add two cars registered to two different accounts (me and my wife)? Thanks!

**Comment by bslefevre** [comment]
I've got the same challenge and solved it by adding my wife's car to my account. Maybe that'll solve this issue for you

**Comment by Farfar** [comment]
> How do I add two cars registered to two different accounts (me and my wife)? Thanks!

For 1.0.42 onwards you just add the integration again and go through the config.

For earlier releases you need to have them all on same account.

**Comment by bruxy70** [comment]
Thanks!
