### ISSUE TITLE
Platform intermittently won't setup.

### ISSUE THREAD

**Issue by markxroberts** [lendy007/homeassistant-skodaconnect#53]
**Describe the bug**
Platform doesn't setup if restart HA too frequently.  Once in a 24 hour period seems to be the maximum.  Is this a limitation of the platform, or can it be fixed?

**Latest working release**
Never worked

**Debug logs**
Unable to prepare setup for platform skodaconnect.device_tracker: Unable to set up component.
20:32:04 – (ERROR) setup.py - message first occurred at 20:32:04 and shows up 41 times
Setup failed for skodaconnect: Integration failed to initialize.
20:30:59 – (ERROR) setup.py
Could not login to Skoda Connect, please check your credentials and verify that the service is working
20:30:59 – (WARNING) skodaconnect (custom integration)
Could not update information: 'serviceInfo'
20:30:59 – (WARNING) /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py
Could not fetch operation list, HTTP status code: 401
20:30:59 – (WARNING) /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py
Received "unauthorized" error while fetching data: 401, message='Unauthorized', url=URL('https://mal-3a.prd.eu.dp.vwg-connect.com/api/rolesrights/operationlist/v3/vehicles/XXXXXXXX/users/XXXXXXX?scope=ALL')
20:30:59 – (WARNING) /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py
Setup of skodaconnect is taking over 10 seconds.
20:30:37 – (WARNING) /usr/local/lib/python3.9/asyncio/events.py - message first occurred at 20:30:14 and shows up 2 times

**Installation:**
 - HA Docker 2021.7.3

**Comment by Farfar** [comment]
There's no issue for me restarting several times per day. However somtimes the backend servers experience poor availability. Especially the token refresh service which might time out and leave you without valid tokens that causes the 401 error.
If you encounter this issue, try to reload the integration from within home assistant. One might need to do this several times when VAG have issues in their system.
