### ISSUE TITLE
Skoda native API returned no cars

### ISSUE THREAD

**Issue by dervitti** [lendy007/homeassistant-skodaconnect#55]
Hi,
after specifying the correct credentials, example.py does not display any errors in the real sense. But no vehicle either. In the Skoda app and online in the Skoda-Connect, however, it can be seen and is fully set up. Any idea what's going wrong?
Many Thanks and greetings 
Vitti

```
DEBUG:skodaconnect.connection:Token for connect verified OK.
DEBUG:skodaconnect.connection:HTTP GET "https://api.connect.skoda-auto.cz/api/v2/garage/vehicles"
DEBUG:skodaconnect.connection:Request for "https://api.connect.skoda-auto.cz/api/v2/garage/vehicles" returned with status code [200]
DEBUG:skodaconnect.connection: Skoda native API returned no cars
```

**Comment by Farfar** [comment]
> Hi,
> after specifying the correct credentials, example.py does not display any errors in the real sense. But no vehicle either. In the Skoda app and online in the Skoda-Connect, however, it can be seen and is fully set up. Any idea what's going wrong?
> Many Thanks and greetings
> Vitti
> 
> ```
> DEBUG:skodaconnect.connection:Token for connect verified OK.
> DEBUG:skodaconnect.connection:HTTP GET "https://api.connect.skoda-auto.cz/api/v2/garage/vehicles"
> DEBUG:skodaconnect.connection:Request for "https://api.connect.skoda-auto.cz/api/v2/garage/vehicles" returned with status code [200]
> DEBUG:skodaconnect.connection: Skoda native API returned no cars
> ```

Not sure really, what model car do you have? I think all models should exist under this API endpoint but some older models might not be migrated.

**Comment by dervitti** [comment]
> Not sure really, what model car do you have? I think all models should exist under this API endpoint but some older models might not be migrated.

It´s a brand new Skoda Superb (SUP.COM iVL&K TS115/1.4A6F)  
The VW Connect Adapter (Version: 0.0.39) in IOBroker (https://github.com/TA2k/ioBroker.vw-connect) is able to fetch the car.

**Comment by Farfar** [comment]
> > Not sure really, what model car do you have? I think all models should exist under this API endpoint but some older models might not be migrated.
> 
> It´s a brand new Skoda Superb (SUP.COM iVL&K TS115/1.4A6F)
> The VW Connect Adapter (Version: 0.0.39) in IOBroker (https://github.com/TA2k/ioBroker.vw-connect) is able to fetch the car.

Can you try an older version, 1.0.3x, and see if that works?
The difference is that the older releases used the VW API to fetch car info and capabilities whereas newer releases use the Skoda native API endpoints. You can also try with your current release but at a different time and see if it's just a temporary issue.

**Comment by dervitti** [comment]
> Can you try an older version, 1.0.3x, and see if that works?

Tried 1.0.37 and with this version everything works as expexted. Thank you
