### ISSUE TITLE
Setup failed for skodaconnect (v1.0.45-rc1)

### ISSUE THREAD

**Issue by hkraal** [lendy007/homeassistant-skodaconnect#57]
Just installed v1.0.45-rc1 after reading the awesome release notes, can't wait to sync my charger speed with solar panel production!

I get the following error on startup sadly;
```
Logger: homeassistant.setup
Source: setup.py:173
First occurred: 9:56:27 PM (1 occurrences)
Last logged: 9:56:27 PM

Setup failed for skodaconnect: Unable to import component: cannot import name 'Connection' from partially initialized module 'skodaconnect' (most likely due to a circular import) (/config/skodaconnect/__init__.py)
```

**Comment by hkraal** [comment]
This problem resolved with the .50 release (IIRC) but the next error popped up. Ultimately it seemed to be caused by me moving the custom_components/skodaconnnect` a directory up making hass think that was the skodaconnnect library which needed to be loaded.

**Comment by Farfar** [comment]
> This problem resolved with the .50 release (IIRC) but the next error popped up. Ultimately it seemed to be caused by me moving the custom_components/skodaconnnect` a directory up making hass think that was the skodaconnnect library which needed to be loaded.

Great, glad to hear 🙂
