### ISSUE TITLE
Integration doesn't work after updating to newest version.

### ISSUE THREAD

**Issue by quantummobile** [lendy007/homeassistant-skodaconnect#61]
**Describe the bug**

Integration doesn't work after updating to newest version.
<img width="587" alt="Screenshot 2021-08-28 at 16 31 37" src="https://user-images.githubusercontent.com/47085307/131219665-c092406f-ce59-4c2b-9159-fe790d674d61.png">

**Latest working release**
If the problem started after updating to a new release, please state latest working release.

**Debug logs**
If applicable, add debug logs. See [README](https://github.com/lendy007/homeassistant-skodaconnect#enable-debug-logging) on how to enable debug logs with response debugging.

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/skodaconnect/__init__.py:197
Integration: Skoda Connect (documentation, issues)
First occurred: 13:57:48 (1 occurrences)
Last logged: 13:57:48

Error setting up entry TMBLE7NS1M8025188 for skodaconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/skodaconnect/__init__.py", line 197, in async_setup_entry
    options={**entry.options, **update[CONF_RESOURCES]}
TypeError: 'list' object is not a mapping
`

**Installation:**
 - Home Assistant variant: [e.g. Hass OS, Docker, Core, Supervised]
 - Python version [e.g. 3.7, 3.8]
 - Python library versions ["python3 -m pip list"]

Home Assistant OS 6.2
Supervisor Version supervisor-2021.06.8
Core Version core-2021.8.8

**Additional context**

**Comment by Farfar** [comment]
Which integration version? 1.0.52?
Is this with clean setup or migrated from 1.0.4x-RC?

**Comment by xMachineHead** [comment]
Hi,
I'm getting the exact same error (both error message and log information) as listed above.

Im running on version 1.0.51 from a fresh install of the Skoda Connect integration via HACS (had to remove the integration since the migration from 1.0.4x-RC broke the configuration)
I'm fairly new to Home Assistant so I do apologize if I've left out any essential information you may need, please let me know if you need me to provide you with more information, logs, screenshot etc.

**Comment by quantummobile** [comment]
> Which integration version? 1.0.52?
> Is this with clean setup or migrated from 1.0.4x-RC?

v1.0.51
Updated from previous version, some .4x

Everything used to work just fine until today I decided to update.

**Comment by Farfar** [comment]
> > Which integration version? 1.0.52?
> > Is this with clean setup or migrated from 1.0.4x-RC?
> 
> v1.0.51
> Updated from previous version, some .4x
> 
> Everything used to work just fine until today I decided to update.

Try removing the configuration under HA integrations (don't uninstall) and re-add config.



> Hi,
> I'm getting the exact same error (both error message and log information) as listed above.
> 
> Im running on version 1.0.51 from a fresh install of the Skoda Connect integration via HACS (had to remove the integration since the migration from 1.0.4x-RC broke the configuration)
> I'm fairly new to Home Assistant so I do apologize if I've left out any essential information you may need, please let me know if you need me to provide you with more information, logs, screenshot etc.

Do you have any configuration left in you configuration.yaml?

**Comment by quantummobile** [comment]
> > > Which integration version? 1.0.52?
> > > Is this with clean setup or migrated from 1.0.4x-RC?
> > 
> > 
> > v1.0.51
> > Updated from previous version, some .4x
> > Everything used to work just fine until today I decided to update.
> 
> Try removing the configuration under HA integrations (don't uninstall) and re-add config.
> 
> > Hi,
> > I'm getting the exact same error (both error message and log information) as listed above.
> > Im running on version 1.0.51 from a fresh install of the Skoda Connect integration via HACS (had to remove the integration since the migration from 1.0.4x-RC broke the configuration)
> > I'm fairly new to Home Assistant so I do apologize if I've left out any essential information you may need, please let me know if you need me to provide you with more information, logs, screenshot etc.
> 
> Do you have any configuration left in you configuration.yaml?

Removing configuration leftovers from configuration.yaml and removing / adding integration, rebooting HA worked for me.

Many thanks!

**Comment by xMachineHead** [comment]
> > > Which integration version? 1.0.52?
> > > Is this with clean setup or migrated from 1.0.4x-RC?
> > 
> > 
> > v1.0.51
> > Updated from previous version, some .4x
> > Everything used to work just fine until today I decided to update.
> 
> Try removing the configuration under HA integrations (don't uninstall) and re-add config.
> 
> > Hi,
> > I'm getting the exact same error (both error message and log information) as listed above.
> > Im running on version 1.0.51 from a fresh install of the Skoda Connect integration via HACS (had to remove the integration since the migration from 1.0.4x-RC broke the configuration)
> > I'm fairly new to Home Assistant so I do apologize if I've left out any essential information you may need, please let me know if you need me to provide you with more information, logs, screenshot etc.
> 
> Do you have any configuration left in you configuration.yaml?

I've tried remove it from HA integrations and re-add the config now, its the same error unfortunately.

This is what I've added to my configuration.yaml:

skodaconnect:
  username: !secret skodaconnect_id
  password: !secret skodaconnect_password
  spin: !secret skodaconnect_spin
  scandinavian_miles: false
  scan_interval:
    minutes: 1
  name:
    (MY VIN-NUMBER): "Skoda Superb iV"

**Comment by xMachineHead** [comment]
> > > Which integration version? 1.0.52?
> > > Is this with clean setup or migrated from 1.0.4x-RC?
> > 
> > 
> > v1.0.51
> > Updated from previous version, some .4x
> > Everything used to work just fine until today I decided to update.
> 
> Try removing the configuration under HA integrations (don't uninstall) and re-add config.
> 
> > Hi,
> > I'm getting the exact same error (both error message and log information) as listed above.
> > Im running on version 1.0.51 from a fresh install of the Skoda Connect integration via HACS (had to remove the integration since the migration from 1.0.4x-RC broke the configuration)
> > I'm fairly new to Home Assistant so I do apologize if I've left out any essential information you may need, please let me know if you need me to provide you with more information, logs, screenshot etc.
> 
> Do you have any configuration left in you configuration.yaml?

Thanks, worked like a charm to re-add config and remove old congirutaion.yaml entires.

**Comment by Farfar** [comment]
It seems to be an issue in how and where I have chosen to store integration settings (in 'data' or in 'options') and recent release does not work correctly in migrating data entrys. I'm working on fixing this but it's a pain since I need to remove and re-add and move between different releases to test.

**Comment by Farfar** [comment]
Version 1.0.52 should work with migration from RC releases as well. I have tested successfully from 1.0.42-RC2 to 1.0.52 and all works as it should.
Configuration.yaml is untested though.
