### ISSUE TITLE
Integration not updating entities

### ISSUE THREAD

**Issue by maccan-tech** [lendy007/homeassistant-skodaconnect#63]
**Describe the bug**
Updated integration using HACS from 1.0.38 to 1.0.52
Removed all of the config in configuration.yaml and did the config flow in integrations.
Config flow worked and I got all of the entities and values.
Then i get this errors when the integration is going to update the entities.
If i reload the integration it fetches the values correctly one time.

**Car**
Skoda Citigo ev

**Latest working release**
1.0.38

**logs**
```
Logger: skodaconnect.connection
Source: /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py:1548
First occurred: August 30, 2021, 1:28:33 PM (953 occurrences)
Last logged: 8:39:45 AM

Something went wrong when refreshing VW-Group API tokens. <!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Access Denied</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat</h3></body></html>
----
Logger: skodaconnect.connection
Source: /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py:745
First occurred: August 30, 2021, 1:33:33 PM (215 occurrences)
Last logged: 8:39:45 AM

Could not fetch StoredVehicleDataResponse, error: 0
Could not fetch StoredVehicleDataResponse, error:
Could not fetch StoredVehicleDataResponse, error: Cannot connect to host msg.volkswagen.de:443 ssl:default [Try again]
----
Logger: skodaconnect.connection
Source: /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py:602
First occurred: August 30, 2021, 1:33:33 PM (189 occurrences)
Last logged: 8:39:45 AM

Received "unauthorized" error while fetching data: 401, message='Unauthorized', url=URL('https://msg.volkswagen.de/fs-car/bs/vsr/v1/skoda/CZ/vehicles/TMBZxxxxxxxxxxxxxx/status')
```

**Installation:**
 - Home Assistant variant: Supervised

**Additional context**

**Comment by ornellino** [comment]
Same issue here, I have the same WARNINGS on log.
Upgraded integration on HACS to 1.0.52.
Removed  entries from configuration.yaml.

Vehicle: Skoda Karoq, Skoda Citigo E IV
HA: 2021.8.7

**Comment by tjafbe** [comment]
I can confirm I also have the exact same issue. This was working fine until I updated yesterday to v1.0.52. The app still works fine. 
My logger shows exactly the same errors.

Oddly enough when I use the "force refresh" switch, it does actually work and updates all my entities. But they do not get updated automatically anymore. Maybe this can point you towards the right direction?

**Comment by Farfar** [comment]
There seems to have been some change that affects the refresh of VW-Group API tokens.



> Oddly enough when I use the "force refresh" switch, it does actually work and updates all my entities. But they do not get updated automatically anymore. Maybe this can point you towards the right direction?

Why this happens is because a set action will cause the library to re-login which will retrieve new tokens.

I am working on a fix. Refresh is preferred since it's faster than new login.

**Comment by Farfar** [comment]
Latest release should have addressed theese issues.

**Comment by tjafbe** [comment]
I just upgraded to v1.0.54. I can confirm I no longer have these issues. Seems to be working again. Thanks a lot @Farfar for the swift action. I really appreciate your great work!
