### ISSUE TITLE
[BUG] Install Error

### ISSUE THREAD

**Issue by terriblefox** [lendy007/homeassistant-skodaconnect#7]
Got this message after install. Installed in custom components.

---

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:420 
Integration: Hass.io (documentation, issues) 
First occurred: 9:15:45 (5 occurrences) 
Last logged: 9:24:57

Component error: skodaconnect - cannot import name 'find_path' from 'utilities' (/usr/local/lib/python3.8/site-packages/utilities/__init__.py)

---

# SkodaConnect
skodaconnect:
    username: xxx@xxxxx.de
    password: xxxxxxxxx
    spin: xxxx
    combustion_engine_heating_duration: <allowed values 10,20,30,40,50,60 (minutes)>
    combustion_engine_climatisation_duration: <allowed values 10,20,30,40,50,60 (minutes)>
    scandinavian_miles: false
    imperial_units: false
    scan_interval:
        minutes: 5
    name:
        tmbjxxxxxxxxx25: 'Ocatvia'
    resources:
        - combustion_engine_heating         
        - combustion_climatisation
        - distance
        - position
        - service_inspection
        - oil_inspection
        - door_locked
        - trunk_locked
        - request_in_progress
        - fuel_level        
        - windows_closed        
        - adblue_level
        - climatisation_target_temperature
        - last_connected
        - combustion_range
        - trip_last_average_speed
        - trip_last_average_fuel_consumption
        - trip_last_duration
        - trip_last_length
        - parking_light
        - door_closed_left_front        
        - door_closed_left_back
        - door_closed_right_front
        - door_closed_right_back
        - trunk_closed
        - window_closed_left_front
        - window_closed_left_back
        - window_closed_right_front
        - window_closed_right_back
        - sunroof_closed
        - service_inspection_km
        - oil_inspection_km
        - outside_temperature
        - electric_climatisation
        - window_heater
        - charging
        - battery_level
        - charging_time_left
        - electric_range
        - combined_range
        - charge_max_ampere
        - climatisation_target_temperature
        - external_power
        - climatisation_without_external_power
        - charging_cable_connected
        - charging_cable_locked
        - trip_last_average_electric_consumption
        - hood_closed
        - combustion_engine_heatingventilation_status
        - vehicleMoving
        - parkingTime
        - energy_flow
        - requests_remaining

**Comment by Farfar** [comment]
Seems like the library helper functions are mixed up with another library. For Hass.io i presume?
I think a file structure change for the skodaconnect library is needed. The quick fix is renaming the utilities.py for skodaconnect but that will most likely only push the problem into the future.

**Comment by terriblefox** [comment]
Ok, I can't see where these things get mixed up. Where can I rename the utilities.py? In the __init__.py?
Can I do something, to help figure out the problem?

**Comment by Farfar** [comment]
> Ok, I can't see where these things get mixed up. Where can I rename the utilities.py? In the **init**.py?
> Can I do something, to help figure out the problem?
> 
> Seems to be hass.io 2020.12.1 issue as it ist the same problem here in the vw plugin thread:
> 
> [robinostlund/homeassistant-volkswagencarnet#223](https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/223)

It's not that simple, the file would need to be renamed and all references in code would need to be changed.
Hold tight, I will update library+integration and publish new releases ASAP.

**Comment by Farfar** [comment]
@terriblefox please test latest release 1.0.26. It should fix this issue.

**Comment by terriblefox** [comment]
deleted the old one and installed new... seems like the same error...


Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:420 
Integration: Hass.io (documentation, issues) 
First occurred: 23:33:55 (1 occurrences) 
Last logged: 23:33:55

Component error: skodaconnect - cannot import name 'find_path' from 'utilities' (/usr/local/lib/python3.8/site-packages/utilities/__init__.py)

**Comment by Farfar** [comment]
> Component error: skodaconnect - cannot import name 'find_path' from 'utilities' (/usr/local/lib/python3.8/site-packages/utilities/**init**.py)

That's really strange since the new release should import from 'skodaconnect.utilities'.
Can you make sure that there's a skodaconnect folder under '/usr/local/lib/python3.8/site-packages/' ?

**Comment by terriblefox** [comment]
Mh im running this in a docker environment ... perhaps this is the problem .. can't find the python folder....

**Comment by Farfar** [comment]
> Mh im running this in a docker environment ... perhaps this is the problem .. can't find the python folder....

I'm not familiar with docker but a quick search tells me you should be able to list the files inside the container with something like:
`docker exec CONTAINER ls /usr/local/lib/python3.8/site-packages/`

**Comment by terriblefox** [comment]
found this. should be the right files...

bash-5.0# ls                                                                                                                                                          
@eaDir                configuration.yaml    fans.yaml             image                 scenes.yaml           switches.yaml                                           
automations.yaml      custom_components     groups.yaml           input_selects.yaml    scripts.yaml          themes                                                  
blueprints            customize.yaml        home-assistant.log    known_devices.yaml    secrets.yaml          tts                                                     
config                deps                  home-assistant_v2.db  media                 skodaconnect.yaml     www                                                     
bash-5.0# ls /usr/local/lib/python3.8/site-packages/                                                                                                                  
hacs_frontend-20201205162459.dist-info               pymitv-1.4.3.dist-info                                      
.....
skodaconnect-1.0.24.dist-info                               
skodaconnect.py

**Comment by Farfar** [comment]
> found this. should be the right files...
> 
> bash-5.0# ls
> @eadir configuration.yaml fans.yaml image scenes.yaml switches.yaml
> automations.yaml custom_components groups.yaml input_selects.yaml scripts.yaml themes
> blueprints customize.yaml home-assistant.log known_devices.yaml secrets.yaml tts
> config deps home-assistant_v2.db media skodaconnect.yaml www
> bash-5.0# ls /usr/local/lib/python3.8/site-packages/
> hacs_frontend-20201205162459.dist-info pymitv-1.4.3.dist-info
> .....
> skodaconnect-1.0.24.dist-info
> skodaconnect.py

I just realised I never actually uploaded the 1.0.26 library to pypi. It's uploaded now if you could please reinstall the component.

**Comment by terriblefox** [comment]
mh no, still...

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:420 
Integration: Hass.io (documentation, issues) 
First occurred: 8:12:29 (1 occurrences) 
Last logged: 8:12:29

Component error: skodaconnect - cannot import name 'find_path' from 'utilities' (/usr/local/lib/python3.8/site-packages/utilities/__init__.py)

**Comment by Farfar** [comment]
> mh no, still...
> 
> Logger: homeassistant.components.hassio
> Source: components/hassio/**init**.py:420
> Integration: Hass.io (documentation, issues)
> First occurred: 8:12:29 (1 occurrences)
> Last logged: 8:12:29
> 
> Component error: skodaconnect - cannot import name 'find_path' from 'utilities' (/usr/local/lib/python3.8/site-packages/utilities/**init**.py)



> mh no, still...
> 
> Logger: homeassistant.components.hassio
> Source: components/hassio/**init**.py:420
> Integration: Hass.io (documentation, issues)
> First occurred: 8:12:29 (1 occurrences)
> Last logged: 8:12:29
> 
> Component error: skodaconnect - cannot import name 'find_path' from 'utilities' (/usr/local/lib/python3.8/site-packages/utilities/**init**.py)

Please use the latest release, 1.0.27.
I noticed I had updated wrong branch so the wrong pypi package was requested (1.0.24 instead of 1.0.26).

**Comment by terriblefox** [comment]
I think now some magic happened. It loaded the config without (nearly none) errors. Had to remove parking time. For now I can't see any entities but I think I have to wait till they refresh.... will give feedback. Thanks you!

**Comment by terriblefox** [comment]
So, this works like a charm now !
<img width="1865" alt="Bildschirmfoto 2020-12-23 um 09 35 22" src="https://user-images.githubusercontent.com/43913179/102976746-50a25880-4502-11eb-8f9f-2cb94f581bd8.png">
Thank you a lot !
