### ISSUE TITLE
Skodaconnect fails to log in

### ISSUE THREAD

**Issue by raczgy** [lendy007/homeassistant-skodaconnect#71]
**Describe the bug**
The integration worked fine for a while but now started to fail at logon.
used version: v1.0.56

**Latest working release**
I'm not sure if it started with this build but with v1.0.56 definitely fails to log on

**Debug logs**
If applicable, add debug logs. See [README](https://github.com/lendy007/homeassistant-skodaconnect#enable-debug-logging) on how to enable debug logs with response debugging.

This error originated from a custom integration.

Logger: custom_components.skodaconnect.config_flow
Source: custom_components/skodaconnect/config_flow.py:277
Integration: Skoda Connect (documentation, issues)
First occurred: 17:21:39 (1 occurrences)
Last logged: 17:21:39

Failed to login due to error: 'Connection' object has no attribute 'validate_login'

**Installation:**
Operating System
Home Assistant OS 6.3
core-2021.9.6
supervisor-2021.09.0

**Additional context**
used with a skoda superb manufactured at 2017

**Comment by Farfar** [comment]
> **Describe the bug**
> The integration worked fine for a while but now started to fail at logon.
> used version: v1.0.56
> 
> **Latest working release**
> I'm not sure if it started with this build but with v1.0.56 definitely fails to log on
> 
> **Debug logs**
> If applicable, add debug logs. See [README](https://github.com/lendy007/homeassistant-skodaconnect#enable-debug-logging) on how to enable debug logs with response debugging.
> 
> This error originated from a custom integration.
> 
> Logger: custom_components.skodaconnect.config_flow
> Source: custom_components/skodaconnect/config_flow.py:277
> Integration: Skoda Connect (documentation, issues)
> First occurred: 17:21:39 (1 occurrences)
> Last logged: 17:21:39
> 
> Failed to login due to error: 'Connection' object has no attribute 'validate_login'
> 
> **Installation:**
> Operating System
> Home Assistant OS 6.3
> core-2021.9.6
> supervisor-2021.09.0
> 
> **Additional context**
> used with a skoda superb manufactured at 2017

Try again later, in a few days. VAG have server problems at the moment.

**Comment by raczgy** [comment]
Ok,
Thank you. If this is the case, please feel free to close the ticket.
György

**Comment by Farfar** [comment]
@raczgy services seems to be up again. Can you verify that everything works again?

**Comment by Farfar** [comment]
Thanks to this issue I realized as well that the reauth flow had an incorrect reference to validate_login that will get fixed in next realease.

**Comment by raczgy** [comment]
Thank You!
The service now available.
