### ISSUE TITLE
Skoda connect fails to install

### ISSUE THREAD

**Issue by dvid481** [lendy007/homeassistant-skodaconnect#72]
After updating home assistent to the latest release 9.4 skoda connect failed to connect.

I have removed the integration.
After that I have manually copied the lasted release to the custom components folder. And tried to run pip install skodaconnect this results in an GCC error.

When I try to add the integration trough settings-> integrations it results in a config flow error.

Could you please help me on this?

**Comment by Farfar** [comment]
> After updating home assistent to the latest release 9.4 skoda connect failed to connect.
> 
> I have removed the integration.
> After that I have manually copied the lasted release to the custom components folder. And tried to run pip install skodaconnect this results in an GCC error.

If you are trying to install manually make sure that you use pip for Python 3.x, i.e. pip3. Installation via HACS is recommended though.

> 
> When I try to add the integration trough settings-> integrations it results in a config flow error.
> 
> Could you please help me on this?

What is the error? Can you provide some debug logs?
There has been some issues with VW servers lately and it might be that the issues aren't resolved.

**Comment by dvid481** [comment]
Thanks for the quick reply.

I'm not sure but after several restarts and installation of another integration I tried to install skodaconnect again from the integrations menu in order to generate a log file. I didn't expect that it would finish successfull. But fortunately it installed successfully. Therefore this issue can be closed.
