### ISSUE TITLE
Can't log into Skoda Connect

### ISSUE THREAD

**Issue by CJA59UK** [lendy007/homeassistant-skodaconnect#73]
This error originated from a custom integration.

Logger: custom_components.skodaconnect.config_flow
Source: custom_components/skodaconnect/config_flow.py:98
Integration: Skoda Connect
First occurred: 16:36:50 (2 occurrences)
Last logged: 16:44:57

Login failed with error: User appears unauthorized

**Debug logs**
2021-09-22 16:44:56 INFO (MainThread) [skodaconnect.connection] Init Skoda Connect library, version 1.1.6
2021-09-22 16:44:56 DEBUG (MainThread) [skodaconnect.connection] Using service https://msg.volkswagen.de
2021-09-22 16:44:57 INFO (MainThread) [skodaconnect.connection] Initiating new login
2021-09-22 16:44:57 DEBUG (MainThread) [skodaconnect.connection] Starting authorization process for client skoda
2021-09-22 16:44:57 DEBUG (MainThread) [skodaconnect.connection] Got redirect to signin-service
2021-09-22 16:44:57 DEBUG (MainThread) [skodaconnect.connection] Start authorization for user colin.j.aitken@gmail.com
2021-09-22 16:44:57 DEBUG (MainThread) [skodaconnect.connection] Finalizing login
2021-09-22 16:44:57 DEBUG (MainThread) [skodaconnect.connection] Unexpected response: 

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport"
          content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <meta name="identitykit" content="loginIdentifier"/>
    <link href="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/emea/1630337143/styles/skoda-theme.css"
          rel="stylesheet"/>
    <link rel="apple-touch-icon" sizes="180x180"
          href="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/emea/1630337143/favicons/skoda/apple-touch-icon.png"/>
    <link rel="icon" type="image/png" sizes="32x32"
          href="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/emea/1630337143/favicons/skoda/favicon-32x32.png"/>
    <link rel="icon" type="image/png" sizes="16x16"
          href="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/emea/1630337143/favicons/skoda/favicon-16x16.png"/>
<script src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/emea/1630337143/javascripts/base/jquery-3.5.0.min.js"></script>
<script type="application/javascript"
        src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/emea/1630337143/javascripts/base/PasswordRevealer.js"></script>
<script type="application/javascript"
        src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/emea/1630337143/javascripts/base/InputFieldSessionPersistence.js"></script>
<script type="application/javascript"
        src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/emea/1630337143/javascripts/base/OnDocumentLoaded.js"></script>
<script type="application/javascript"
        src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/emea/1630337143/javascripts/base/TimeElapsedCounter.js"></script>
<script type="application/javascript"
        src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/emea/1630337143/javascripts/base/ErrorRemover.js"></script>
<script type="application/javascript"
        src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/emea/1630337143/javascripts/base/consent.js"></script>

<script type="application/javascript">
//<![CDATA[
    new OnDocumentLoaded(document, callback);

    function callback() {
        addHideMessageEventListener('[type="password"]');
        addHideMessageEventListener('[type="text"]');
        addHideMessageEventListener('[type="email"]');

        new PasswordRevealer(document, document.querySelector('[type="password"]'), '#input_password_revealer');
        new InputFieldSessionPersistence(document.getElementById("input_email"), window);
    }

    function addHideMessageEventListener(selector) {
        var element = document.querySelector(selector);
        if (element) {
            element.addEventListener("keydown", hideMessage);
        }
    }

    function hideMessage() {
        new ErrorRemover(document);
    }

    function isNotIE() {
        try {
            var ua = window.navigator.userAgent;
            var msie = ua.indexOf("MSIE ");
            var isIEUpToVersion11 = msie > 0;
            var isIEFromVersion11 = !!navigator.userAgent.match(/Trident.*rv\:11\./);
            var isIE = isIEUpToVersion11 || isIEFromVersion11;
            return !isIE;
        } catch (e) {
            return true;
        }
    }
//]]>
</script></head>
<body>

<div id="page-container-background">
</div>

<div class="body-container">
        <div id="header">
            <div></div>
        </div>

    <div class="page-container">
        <div class="page-content">
            <div class="hide spacer-top" ></div>

            <div id="legal-entity" class="legal-entity">
                <div class="legal-entity-logo"></div>
                <div id="legal-entity-name"
                     class="legal-entity-name">ŠKODA ID</div>
            </div>

<form class="content" id="emailPasswordForm"
      name="emailPasswordForm"
      method="POST"
      novalidate="true"
      action="/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/login/identifier">
    <div id="title" class="title">
        <div class="primary-title">Welcome</div>
        <div class="sub-title">to ŠKODA App &amp; Portal.</div>
    </div>
    <input type="hidden" id="csrf" name="_csrf" value="d0a4f3c0-f8a3-4f45-b1a4-52706e83f9ad"/>
    <input type="hidden" id="input_relayState" name="relayState" value="456a0f40f8c4bf0585bbd4a73a9227ec5b5fc1ba"/>
    <input type="hidden" id="hmac" name="hmac" value="7854d7ee72841039a7e8c68c56a0022b003f510ff74c0e5267bcb23772c7eec5"/>
    <div class="inputs">
<div class="group">
    <input
            id="input_email"
            name="email"
            type="email"
            required="true"
            autofocus="true"
                onkeyup="this.setAttribute('input-value',this.value)"
            
            
            
    />
    <span class="bar"></span>
    <label for="input_email">Email</label>
    

</div>
    </div>
    <div class="btn-group-single">
<button
        id="next-btn"
        class="btn zenith-button btn-active"
        type="submit"
        
>
    Next
</button>
    </div>
    <div class="link">
        <a id="signup-link"
           class="zenith-link"
           href="/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/register/identifier?relayState=456a0f40f8c4bf0585bbd4a73a9227ec5b5fc1ba">
        Create account
        </a>
    </div>

    <script type="application/javascript"
            src="https://cdn.emea.vwapps.io/assets/be108820-9b1a-4906-a2e1-3f39150c43b7/production/emea/1630337143/javascripts/base/InputFieldsButtonEnabler.js"></script>
    <script>
        new OnDocumentLoaded(document, callback);

        function callback() {
            new InputFieldsButtonEnabler(document.querySelector("#input_email"), document.querySelector("#next-btn"));
        }
    </script>
</form>

            <div class="hide spacer-bottom" ></div>

            <footer>

    <ul>
        <li><a href="/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/imprint-page?relayState=456a0f40f8c4bf0585bbd4a73a9227ec5b5fc1ba"
               id="imprint">Imprint</a></li>
        <li><a href="/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/termsOfUse-page?relayState=456a0f40f8c4bf0585bbd4a73a9227ec5b5fc1ba"
               id="terms-of-use">Terms of Use</a></li>
        <li><a href="/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/dataPrivacy-page?relayState=456a0f40f8c4bf0585bbd4a73a9227ec5b5fc1ba"
               id="data-privacy">Data Privacy Policy</a></li>
        <li><a href="/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/cookiePolicy-page?relayState=456a0f40f8c4bf0585bbd4a73a9227ec5b5fc1ba"
               id="cookie-policy">Cookie Policy</a></li>
        <li><a href="/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/licenses-page?relayState=456a0f40f8c4bf0585bbd4a73a9227ec5b5fc1ba"
               id="licenses">3rdParty Licenses</a></li>
    </ul>
            </footer>
        </div>
    </div>
            <footer>

    <ul>
        <li><a href="/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/imprint-page?relayState=456a0f40f8c4bf0585bbd4a73a9227ec5b5fc1ba"
               id="imprint">Imprint</a></li>
        <li><a href="/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/termsOfUse-page?relayState=456a0f40f8c4bf0585bbd4a73a9227ec5b5fc1ba"
               id="terms-of-use">Terms of Use</a></li>
        <li><a href="/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/dataPrivacy-page?relayState=456a0f40f8c4bf0585bbd4a73a9227ec5b5fc1ba"
               id="data-privacy">Data Privacy Policy</a></li>
        <li><a href="/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/cookiePolicy-page?relayState=456a0f40f8c4bf0585bbd4a73a9227ec5b5fc1ba"
               id="cookie-policy">Cookie Policy</a></li>
        <li><a href="/signin-service/v1/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com/licenses-page?relayState=456a0f40f8c4bf0585bbd4a73a9227ec5b5fc1ba"
               id="licenses">3rdParty Licenses</a></li>
    </ul>
            </footer>
</div>
</body>
</html>

2021-09-22 16:44:57 WARNING (MainThread) [skodaconnect.connection] Invalid credentials or invalid configuration. Make sure you have entered the correct credentials
2021-09-22 16:44:57 ERROR (MainThread) [custom_components.skodaconnect.config_flow] Login failed with error: User appears unauthorized
2021-09-22 16:47:11 ERROR (MainThread) [homeassistant.components.upnp] Error requesting RBR350(Gateway) data: 

**Installation:**
 - Home Assistant variant: [Supervised] Version core-2021.9.7

I can definitely log into the Skoda Connect website without any issues

**Comment by kjbstar** [comment]
Same here, since a few days.

**Comment by Farfar** [comment]
Try setting a new password in the Skoda Connect portal. The login fails after the integration has provided your password, it looks like it gets redirected back to the login page.

**Comment by mookkari** [comment]
Same problem here with homeassistant-seatconnect after HA was restarted yesterday. Password change did not not solve the issue.
Issue also noticed in seatconnect fork: https://github.com/Farfar/homeassistant-seatconnect/issues/4

**Comment by Farfar** [comment]
I would need full debug logs from someone with this issue, doesn't matter if it's for the Seat Connect fork or Skoda Connect.
The parts I am interested in is from "Finalizing login" up until the error. (different log messages for Seat Connect, might need whole log).

**Comment by Brephlas** [comment]
Had the same issue yesterday (after applying HassOS update) and a password change did not work. 
According to the logs the password did not seem to be the problem, the error message i found was "API token request failed." 
However, after reinstalling the integration it worked again. 
Unfortunately, because of this I can't provide the log since the reinstallation included a restart of HA.

**Comment by CJA59UK** [comment]
Ok My fault when I logged onto the android app there were some things I had to OK and now the integration is OK. Thanks

**Comment by mookkari** [comment]
I do not have anything specific to accept in Seat Connect Android App or in my.seat web page. Both are working OK. But seatconnect HA plugin does not work anymore after HA reboot yesterday. Did everyone else managed to make skodaconnect working after accepting something in Android App?

**Comment by Farfar** [comment]
> I do not have anything specific to accept in Seat Connect Android App or in my.seat web page. Both are working OK. But seatconnect HA plugin does not work anymore after HA reboot yesterday. Did everyone else managed to make skodaconnect working after accepting something in Android App?

Continue in Seat Connect issue please.
