### ISSUE TITLE
Model image for Enyaq iV missing?

### ISSUE THREAD

**Issue by tigers75** [lendy007/homeassistant-skodaconnect#76]
Hi, the docs says that:
```
What is working, all cars
[...]
Model image, URL in 1080 resolution
```
I configured the plug in in Home assistant and everything is OK and works well, except the image, I can't find it anywhere but I don't know if I'm doing something wrong.
I have a Enyaq iV 60 model.

**Comment by Farfar** [comment]
> Hi, the docs says that:
> 
> ```
> What is working, all cars
> [...]
> Model image, URL in 1080 resolution
> ```
> 
> I configured the plug in in Home assistant and everything is OK and works well, except the image, I can't find it anywhere but I don't know if I'm doing something wrong. I have a Enyaq iV 60 model.

It should be included as an attribute for the device tracker. But the Enyaq device tracker is none existing at the moment.
Will fix in upcoming release

**Comment by tigers75** [comment]
Thanks for the answer. Let me know if I can help with testing or troubleshooting, at the moment everything works great, better than the stock app.

**Comment by Farfar** [comment]
Latest versions contain separate sensors for large and small image

**Comment by flopp999** [comment]
> Latest versions contain separate sensors for large and small image

I do not see images I only see URL.
I am new to HA so it may be that I don't understand how it works :)
I tried to use entity as Picture element card but it doesn't work.
![image](https://user-images.githubusercontent.com/21694965/192205658-79497782-5cbc-4e42-8cf2-66f558ba44c9.png)
