### ISSUE TITLE
AttributeError: 'Vehicle' object has no attribute 'is_model_image_supported'

### ISSUE THREAD

**Issue by robertkalinowski** [lendy007/homeassistant-skodaconnect#85]
The error causes no position is reported and all data are not refreshed automatically, to refresh them there is a need to load the integration once more.

Logger: homeassistant
Source: custom_components/skodaconnect/__init__.py:678
Integration: Skoda Connect (documentation, issues)
First occurred: 12:11:40 (2 occurrences)
Last logged: 12:12:40

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 456, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 496, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/skodaconnect/__init__.py", line 678, in device_state_attributes
    if self.vehicle.is_model_image_supported:
AttributeError: 'Vehicle' object has no attribute 'is_model_image_supported'

**Comment by Farfar** [comment]
Update to latest integration and this should be fixed.

**Comment by robertkalinowski** [comment]
How to update, I do not see any update option in integrations or HACS

**Comment by Farfar** [comment]
There should be an option to either update to latest release (1.0.60 right now). Otherwise you can try to press update information:
![image](https://user-images.githubusercontent.com/1235384/140058525-5678cb74-9fa5-4e67-bb54-326041c6bd99.png)

**Comment by robertkalinowski** [comment]
Thanks, there was no update option like places by you, only Install, so I installed once more and it is resolved now.  Anyhow screenshot similar like presented by you does not exist in my setup, how you get it?

In HACS I see it like this

![Screenshot 2021-11-03 at 13 45 14](https://user-images.githubusercontent.com/20813438/140062458-41f386c0-9ce4-4b9a-971f-adffeac6f5b3.png)

**Comment by Farfar** [comment]
> Thanks, there was no update option like placed by you, only Install, so I installed once more and it is resolved now. Anyhow screenshot similar like presented by you does not exist in my setup, how you get it?
> 
> In HACS I see it like this
> 
> ![Screenshot 2021-11-03 at 13 45 14](https://user-images.githubusercontent.com/20813438/140062458-41f386c0-9ce4-4b9a-971f-adffeac6f5b3.png)

In Home Assistant left hand menu, choose "HACS" and then "Integrations". That should list all installed integrations and give you that look as in my picture.

**Comment by robertkalinowski** [comment]
This is exactly this what I shared....
![Screenshot 2021-11-03 at 13 58 06](https://user-images.githubusercontent.com/20813438/140064164-b78c48da-c72d-43ac-b758-f7707208c10f.png)

**Comment by robertkalinowski** [comment]
maybe it is because I always have information status that HACS is launching and in integrations I see on the list all possible integrations and not only the one installed by me

**Comment by Farfar** [comment]
> This is exactly this what I shared.... ![Screenshot 2021-11-03 at 13 58 06](https://user-images.githubusercontent.com/20813438/140064164-b78c48da-c72d-43ac-b758-f7707208c10f.png)

Sorry, Hard to know which view it is since I don't know your language.
The first x number of repositories shown are the new ones. If you press the top right menu you can choose to dismiss all new repos. Then it should only show installed repositories.

**Comment by Farfar** [comment]
> maybe it is because I always have information status that HACS is launching and in integrations I see on the list all possible integrations and not only the one installed by me

If my above answer doesn't limit the view to only installed repos then it might be an issue with HACS
