### ISSUE TITLE
Electric climatization does not track status after activation

### ISSUE THREAD

**Issue by StoricU** [lendy007/homeassistant-skodaconnect#86]
After I updated a few days ago, I have noticed that the electric_climatisation switch turn back off after being turned on.
On the previous release I was using, the switch stayed on until the car finished heating/cooling.
Is this not possible now?

Also the sensor climatisation_time_left is not working.
"This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device."
Is it not supported any more?

**Comment by Farfar** [comment]
Should be fixed in latest release
