### ISSUE TITLE
Request_result is shown as graph and wrong result in charger_max_ampere

### ISSUE THREAD

**Issue by loeffelpan** [lendy007/homeassistant-skodaconnect#87]
Hi,

today i had a strange situation with your integration.
I have an automation to set charger to Max/16A for my Superb iV in case off connecting the charging cable not at home. Works basically. This time the car was charging but slow.

At home I tried to recapture what happened. During that investigation I saw that state of request_result isn‘t shown in the history anymore. There is an empty graqh instead.

Maybe you could fix this one to make it easier to investigate that strange situation.

**Comment by loeffelpan** [comment]
Any update on this?
Would be really helpful to see a history of "request_result" with timestamp to investigate the other issue i've mentioned.

**Comment by Farfar** [comment]
Since the result isn't a numeric value Home Assistant won't show the history of the value. Your best option would be to create a template sensor that takes the state and translates it to something useful and traceable. For example '0' = Success and 1, 2, 3 etc for failure codes.
What I can do is add a timestampt attribute that corresponds to when the latest status was set.

**Comment by loeffelpan** [comment]
Thanks for your answer.
Sounds like there could only be a binary and a non-binary numeric sensor.
But there are many sensors (non-binary) with randon text states. For example in the iPad-Integration. Maybe there is a way to make a non-numeric sensor showing in the history?

![E4EB2914-2271-4B19-923D-4755CA6E3F20](https://user-images.githubusercontent.com/34661317/142151920-b277dff9-d5bc-4a08-ab56-95643d94f4ad.jpeg)

**Comment by Farfar** [comment]
> Thanks for your answer. Sounds like there could only be a binary and a non-binary numeric sensor. But there are many sensors (non-binary) with randon text states. For example in the iPad-Integration. Maybe there is a way to make a non-numeric sensor showing in the history?
> 
> ![E4EB2914-2271-4B19-923D-4755CA6E3F20](https://user-images.githubusercontent.com/34661317/142151920-b277dff9-d5bc-4a08-ab56-95643d94f4ad.jpeg)



> Thanks for your answer. Sounds like there could only be a binary and a non-binary numeric sensor. But there are many sensors (non-binary) with randon text states. For example in the iPad-Integration. Maybe there is a way to make a non-numeric sensor showing in the history?
> 
> ![E4EB2914-2271-4B19-923D-4755CA6E3F20](https://user-images.githubusercontent.com/34661317/142151920-b277dff9-d5bc-4a08-ab56-95643d94f4ad.jpeg)

You are correct, I redact my statement :)
Will take a look at why this happens, might be because of how the sensor is initialized and it's initial value.

**Comment by Farfar** [comment]
This should be fixed in latest release. You need to rename the device (vehicle) though (or remove the affected entity and all history in the database) for the history correction to take effect.

**Comment by loeffelpan** [comment]
Looks beautiful. Thanks.
I simply droped my DB and start with clean stats for all entities.
