### ISSUE TITLE
[BUG] Invalid config for [skodaconnect]

### ISSUE THREAD

**Issue by ingeniumdesign** [lendy007/homeassistant-skodaconnect#9]
Hi all and thanks for the very nice Plugin!

But i have two resources with Error:

```
- vehicleMoving
- parkingTime
```
_Invalid config for [skodaconnect]_

After i disable this two, the Plugin works.

Thanks for help.

**Comment by Farfar** [comment]
README is updated, it's not a bug rather than two sensors that get enabled together with position.
