### ISSUE TITLE
Charger Max Ampere is displayed as sensor in home assistant instead of controls on the skoda enyaq.  when this function is off in the app it indicates maximum A, and when it is on in the app redused A. can this become a control in HA?

### ISSUE THREAD

**Issue by sc0ps** [lendy007/homeassistant-skodaconnect#90]
![picture_1637193945993.png](https://user-images.githubusercontent.com/83918766/142304700-a194080e-6dae-40cb-b646-70497fe35c38.png)

**Comment by Farfar** [comment]
For the moment no. Other cars have the ability to set this to a integer value, 1-254, and I would have to write separating logic etc to enable this.
It might be enabled in the future though.
