### ISSUE TITLE
skoda enyaq cable locked colored status icon

### ISSUE THREAD

**Issue by sc0ps** [lendy007/homeassistant-skodaconnect#91]
cable locked status is incorrectly indicated when color icon based on state is on.  with the enyaq, the cable is only locked when it is plugged into the car and then the car is locked.  colored icon based on status should therefore be active, with status locked

![Screenshot_20211119-184205_Home Assistant.jpg](https://user-images.githubusercontent.com/83918766/142669532-6b349154-5241-44f9-940a-4b21f9c2da48.jpg)

Relase 1.0.62

**Comment by Farfar** [comment]
> cable locked status is incorrectly indicated when color icon based on state is on. with the enyaq, the cable is only locked when it is plugged into the car and then the car is locked. colored icon based on status should therefore be active, with status locked
> 
> ![Screenshot_20211119-184205_Home Assistant.jpg](https://user-images.githubusercontent.com/83918766/142669532-6b349154-5241-44f9-940a-4b21f9c2da48.jpg)
> 
> Relase 1.0.62

I'm not sure I understand what you are trying to explain.
According to your picture it looks correct, the icon shows unlocked padlock when state is unlocked. Or is this incorrect?

**Comment by Farfar** [comment]
If you mean that the state is "off" when it's locked this is just how Home Assistant works. See https://www.home-assistant.io/integrations/binary_sensor/
