### ISSUE TITLE
Error message from HA 2021.12 "implements device_state_attributes"

### ISSUE THREAD

**Issue by northpower25** [lendy007/homeassistant-skodaconnect#95]
**Describe the bug**
Error Message with HA 2021.12

**Latest working release**
If the problem started after updating to a new release, please state latest working release.

**Debug logs**
Entity binary_sensor.superb_sty_td110_2_0a7f_doors_locked (<class 'custom_components.skodaconnect.binary_sensor.SkodaBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.superb_sty_td110_2_0a7f_door_closed_left_front (<class 'custom_components.skodaconnect.binary_sensor.SkodaBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.superb_sty_td110_2_0a7f_door_closed_right_front (<class 'custom_components.skodaconnect.binary_sensor.SkodaBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.superb_sty_td110_2_0a7f_door_closed_left_back (<class 'custom_components.skodaconnect.binary_sensor.SkodaBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.superb_sty_td110_2_0a7f_trunk_locked (<class 'custom_components.skodaconnect.binary_sensor.SkodaBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
**Installation:**
 - Home Assistant variant: Hass OS

**Additional context**

**Comment by tigers75** [comment]
I'm getting the same error. What does it mean? Is there something we can do to fix it?

**Comment by dolenec** [comment]
![image](https://user-images.githubusercontent.com/16633222/150001799-28c1750a-9a8f-4757-b048-89c8040c7861.png)

Logger: skodaconnect.connection
Source: /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py:1128
First occurred: 12:51:00 (1 occurrences)
Last logged: 12:51:00

Could not fetch pre-heating, error: 'NoneType' object has no attribute 'get'

![image](https://user-images.githubusercontent.com/16633222/150001838-bcc79784-9fd8-4b6a-bbb7-d7eaf9c424f4.png)

Logger: skodaconnect.connection
Source: /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py:984
First occurred: 12:51:00 (1 occurrences)
Last logged: 12:51:00

Could not fetch position, error: 'NoneType' object has no attribute 'get'

![image](https://user-images.githubusercontent.com/16633222/150001914-cea3c65e-7614-40e3-b11e-bd33357b5da3.png)

Logger: skodaconnect.connection
Source: /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py:948
First occurred: 12:50:40 (1 occurrences)
Last logged: 12:50:40

Could not fetch trip statistics, HTTP status code: 500

![image](https://user-images.githubusercontent.com/16633222/150002052-63c8e47a-5b61-4f58-86a7-ec278d799166.png)

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 09:18:18 (47 occurrences)
Last logged: 09:19:11

Entity sensor.skoda_octavia_4_oil_inspection_distance (<class 'custom_components.skodaconnect.sensor.SkodaSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.octavia_4_model_image_url_large (<class 'custom_components.skodaconnect.sensor.SkodaSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.skoda_octavia_4_outside_temperature (<class 'custom_components.skodaconnect.sensor.SkodaSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.skoda_octavia_4_last_connected (<class 'custom_components.skodaconnect.sensor.SkodaSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.unifi (<class 'custom_components.my_unifi.sensor.UnifiSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by Farfar** [comment]
> ![image](https://user-images.githubusercontent.com/16633222/150001799-28c1750a-9a8f-4757-b048-89c8040c7861.png)
> 
> Logger: skodaconnect.connection Source: /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py:1128 First occurred: 12:51:00 (1 occurrences) Last logged: 12:51:00
> 
> Could not fetch pre-heating, error: 'NoneType' object has no attribute 'get'
> 
> ![image](https://user-images.githubusercontent.com/16633222/150001838-bcc79784-9fd8-4b6a-bbb7-d7eaf9c424f4.png)
> 
> Logger: skodaconnect.connection Source: /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py:984 First occurred: 12:51:00 (1 occurrences) Last logged: 12:51:00
> 
> Could not fetch position, error: 'NoneType' object has no attribute 'get'
> 
> ![image](https://user-images.githubusercontent.com/16633222/150001914-cea3c65e-7614-40e3-b11e-bd33357b5da3.png)
> 
> Logger: skodaconnect.connection Source: /usr/local/lib/python3.9/site-packages/skodaconnect/connection.py:948 First occurred: 12:50:40 (1 occurrences) Last logged: 12:50:40
> 
> Could not fetch trip statistics, HTTP status code: 500
> 
> ![image](https://user-images.githubusercontent.com/16633222/150002052-63c8e47a-5b61-4f58-86a7-ec278d799166.png)
> 
> Logger: homeassistant.helpers.entity Source: helpers/entity.py:549 First occurred: 09:18:18 (47 occurrences) Last logged: 09:19:11
> 
> Entity sensor.skoda_octavia_4_oil_inspection_distance (<class 'custom_components.skodaconnect.sensor.SkodaSensor'>) implements device_state_attributes. Please report it to the custom component author. Entity sensor.octavia_4_model_image_url_large (<class 'custom_components.skodaconnect.sensor.SkodaSensor'>) implements device_state_attributes. Please report it to the custom component author. Entity sensor.skoda_octavia_4_outside_temperature (<class 'custom_components.skodaconnect.sensor.SkodaSensor'>) implements device_state_attributes. Please report it to the custom component author. Entity sensor.skoda_octavia_4_last_connected (<class 'custom_components.skodaconnect.sensor.SkodaSensor'>) implements device_state_attributes. Please report it to the custom component author. Entity sensor.unifi (<class 'custom_components.my_unifi.sensor.UnifiSensor'>) implements device_state_attributes. Please report it to the custom component author.

First N errors are not relevant to this bug, when there's problems with the API you will get a number of errors. Since there's new API issues now and then all errors doesn't have relevant info.

Latest commit have fix for this bug repoet. It's untested though so not released yet.
If someone want to test latest commit, feel free and report back. Otherwise wait for next release.

**Comment by Farfar** [comment]
Fixed in 1.0.63
